ash-rs/ash

- ash/src/device.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/26)
> Add ds clear and image resolve commands

- ash/Cargo.toml
- ash/src/device.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/29)
> Added cmd_fill_buffer and cmd_update_buffer

- ash/Cargo.toml
- ash/src/device.rs
@MaikKlein I hope that's how it's done :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/30)
> Added (invalidate|flush)_mapped_memory_ranges

- ash/src/device.rs
- ash/src/vk.rs
* Add `cmd_clear_attachments'  to `Device`
* Derive `Copy` for a few structs (where it seems reasonable)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/32)
> Clear attachments command and Copy derives

- ash/Cargo.toml
- ash/src/device.rs
cc @AlphaModder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/34)
> Added CreateBufferView

- ash/src/vk.rs
Related to #33  (And keeps it open when merged)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/35)
> Fix xcb_window_t and X11's Window type definition

- ash/Cargo.toml
- ash/src/entry.rs
- ash/src/extensions/ios_surface.rs
- ash/src/extensions/macos_surface.rs
- ash/src/extensions/mod.rs
- ash/src/vk.rs
It will enable Vulkan availability on macOS/iOS with MoltenVK installed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/36)
> Add MoltenVK support on macOS/iOS

- ash/src/device.rs
For [gfx-rs#1622](https://github.com/gfx-rs/gfx/pull/1622).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/37)
> Add `cmd_push_constants` to Device

- ash/src/device.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/39)
> Add query related functions

- ash/src/device.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/40)
> Fix push constant size (length of bytes instead of DWORDs)

- ash/src/entry.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/43)
> Nicer Entry implementation

- ash/src/entry.rs
Another minor refactor of entry.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/48)
> Entry LIB_PATH

- ash/src/device.rs
fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/54)
> Implement Device::destroy_buffer_view

- ash/src/instance.rs
Fixes #55
also bumps the version in anticipation of a new release ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/56)
> Expose get_physical_device_image_format_properties

- ash/Cargo.toml
- ash/src/device.rs
- Expose `cmd_set_line_width`
- Bump version to 0.24.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/63)
> Expose `cmd_set_line_width`

- ash/Cargo.toml
- ash/src/device.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/64)
> Expose get_image_subresource_layout

- ash/Cargo.toml
- ash/src/device.rs
Just adds a few more dynamic state commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/65)
> Add more dynamic states

- ash/Cargo.toml
- ash/src/entry.rs
- ash/src/lib.rs
These changes are backwards compatible with older versions.
Signed-off-by: Hal Gentz <zegentzy@protonmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/77)
> [WIP] Adds support for using custom ways to load the vulkan dynamic libraries.

- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/86)
> Port of examples

- ash/src/device.rs
- ash/src/instance.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/87)
> Add new functions from 1.1

- .gitignore
- generator/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/97)
> pin vk-parse to crates.io

- ash/src/device.rs
Fixes #105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/106)
> Expose cmd_copy_query_pool_results

- ash/src/vk.rs
- generator/src/lib.rs
Fixes #121.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/123)
> More traits for dispatchable handles

- ash/src/vk.rs
- generator/src/lib.rs
Fixes #116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/129)
> Fix nonsense Debug impl on non-char static arrays

- ash/src/device.rs
- ash/src/extensions/surface.rs
- ash/src/extensions/swapchain.rs
- ash/src/instance.rs
Fixes #94 (unless I missed something)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/131)
> Add missing unsafe qualifiers

- ash/src/entry.rs
- ash/src/extensions/android_surface.rs
- ash/src/extensions/debug_marker.rs
- ash/src/extensions/debug_report.rs
- ash/src/extensions/debug_utils.rs
- ash/src/extensions/display_swapchain.rs
- ash/src/extensions/ios_surface.rs
- ash/src/extensions/macos_surface.rs
- ash/src/extensions/surface.rs
- ash/src/extensions/swapchain.rs
- ash/src/extensions/wayland_surface.rs
- ash/src/extensions/win32_surface.rs
- ash/src/extensions/xcb_surface.rs
- ash/src/extensions/xlib_surface.rs
- ash/src/instance.rs
- ash/src/lib.rs
- ash/src/version.rs
- ash/src/vk.rs
- examples/src/lib.rs
- generator/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/137)
> Implement panicking function pointers

- ash/src/vk.rs
- generator/src/lib.rs
This clarifies generated documentation and removes one more unnecessary C type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/124)
> Flatten vk.rs module structure and use f32

- ash/src/extensions/swapchain.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
Conservative approach to #41. Are there any other cases where information is currently being lost?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/132)
> Expose suboptimal results from swapchain operations

- ash/src/vk.rs
- generator/src/lib.rs
This is from discussions in original PR. I'll address the p_next in next PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/143)
> Builder pattern: Bool32 -> bool + edge cases.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/148)
> Add mac to travis

- .travis.yml
- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/android_surface.rs
- ash/src/extensions/debug_marker.rs
- ash/src/extensions/debug_report.rs
- ash/src/extensions/debug_utils.rs
- ash/src/extensions/display_swapchain.rs
- ash/src/extensions/ios_surface.rs
- ash/src/extensions/macos_surface.rs
- ash/src/extensions/surface.rs
- ash/src/extensions/swapchain.rs
- ash/src/extensions/wayland_surface.rs
- ash/src/extensions/win32_surface.rs
- ash/src/extensions/xcb_surface.rs
- ash/src/extensions/xlib_surface.rs
- ash/src/util.rs
- ash/tests/display.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
- generator/src/lib.rs
- rustfmt.toml
This PR:
- Formats entire Ash codebase using rustfmt
- Adds the rustfmt to travis
- Removes a nightly feature from rustfmt.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/153)
> Rustfmt in Ash

- ash/src/vk.rs
- generator/src/lib.rs
ash-vma requires function pointers of vulkan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/161)
> Public export function pointers

- .travis.yml
- ash/src/entry.rs
- ash/src/vk.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
- generator/src/lib.rs
Needed to prevent spurious failures in new PRs.
> Update to latest rustfmt

- ash/src/device.rs
Fixes https://github.com/MaikKlein/ash/issues/174
> Add event functions

- ash/src/extensions/khr/surface.rs
- examples/src/lib.rs
> Return VkResult from get_physical_device_surface_support

- ash/src/extensions/khr/wayland_surface.rs
- ash/src/extensions/khr/win32_surface.rs
- ash/src/extensions/khr/xcb_surface.rs
- ash/src/extensions/khr/xlib_surface.rs
> Expose get_physical_device_*_presentation_support_khr

- ash/src/vk.rs
- generator/src/lib.rs
> Make handle and bitflags constructor functions const

- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/ext/debug_report.rs
- ash/src/extensions/ext/debug_utils.rs
- ash/src/extensions/khr/android_surface.rs
- ash/src/extensions/khr/surface.rs
- ash/src/extensions/khr/swapchain.rs
- ash/src/extensions/khr/wayland_surface.rs
- ash/src/extensions/khr/win32_surface.rs
- ash/src/extensions/khr/xcb_surface.rs
- ash/src/extensions/khr/xlib_surface.rs
- ash/src/extensions/mvk/ios_surface.rs
- ash/src/extensions/mvk/macos_surface.rs
- ash/src/extensions/nv/ray_tracing.rs
- ash/src/instance.rs
- ash/tests/constant_size_arrays.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
> Replace mem::uninitialized with mem::zeroed

- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
> Aloucks fix example asset loading

- ash/src/vk.rs
- generator/src/lib.rs
The generator needed a few changes. *Note* the generator really needs a cleanup.
> Update VulkanHeaders to 1.1.117

- ash/src/extensions/khr/mod.rs
- ash/src/extensions/khr/push_descriptor.rs
This PR adds support for `VK_KHR_push_descriptor` extension.
ref: https://github.com/MaikKlein/ash/issues/178
> Support VK_KHR_push_descriptor

- ash/src/vk.rs
- generator/src/lib.rs
> Fix XCB types

- ash/src/extensions/khr/draw_indirect_count.rs
- ash/src/extensions/khr/mod.rs
I also wanted to implement VK_AMD_draw_indirect_count at the same time considering it's the same API, but there is no "amd" under `extension`. If everything is fine with this PR, just tell me and I'll do the copy pasting. ;)
> Implement VK_KHR_draw_indirect_count

- ash/src/extensions/ext/metal_surface.rs
- ash/src/extensions/ext/mod.rs
Fixes https://github.com/MaikKlein/ash/issues/221
cc https://github.com/norse-rs/ash-window/issues/8
> Add metal surface extension

- examples/src/lib.rs
See: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/LAYER_CONFIGURATION.md#validation-layer-overview
> Switch to `VK_LAYER_KHRONOS_validation`

- examples/src/lib.rs
This patch changes the example to use the DebugUtils extension instead of DebugReport. Beyond the basic message, additional info provided by DebugUtils is not printed, in order to keep things short and sweet. Let me know if additional info should be printed too. 
[x] ran `cargo fmt`
[x] ran `triangle` and `texture` binaries
> Use DebugUtils instead of DebugReport in example.

- ash/src/vk/const_debugs.rs
- ash/src/vk/definitions.rs
- ash/src/vk/enums.rs
- ash/src/vk/extensions.rs
- generator/Cargo.toml
Hi @MaikKlein 
I still had these sitting locally and recall reading somewhere that it'd be nice to keep Ash somewhat updated. Seems to be vendor changes only so I doubt how immediately useful it is though :)
> Update Vulkan-Headers to 1.2.166

- ash/src/extensions/khr/surface.rs
> rename parameter of get_physical_device_surface_support 

- ash/src/vk/const_debugs.rs
- ash/src/vk/definitions.rs
- ash/src/vk/extensions.rs
Let's stay up-to-date, no matter how small the changes :)
> Update Vulkan-Headers to 1.2.168

- ash/src/extensions/ext/full_screen_exclusive.rs
- ash/src/extensions/ext/mod.rs
Another extension for the collection.
> Add VK_EXT_full_screen_exclusive extension

- ash/src/vk/definitions.rs
- generator/src/lib.rs
> generator: Use lifetime borrows instead of raw pointers in pp_geometries

- ash-window/src/lib.rs
- ash/src/device.rs
- ash/src/entry.rs
- ash/src/entry_libloading.rs
- ash/src/instance.rs
- ash/src/lib.rs
- ash/src/util.rs
Still had this in stash locally, might be nice for the next release.
> Use intradoc-links and explain the various loading methods

- ash-window/LICENSE-APACHE
- ash-window/LICENSE-MIT
- ash/LICENSE-APACHE
- ash/LICENSE-MIT
... so that the license files appear in downloaded crates.
> Adds LICENSE-* files to crate subdirectories

- ash/src/device.rs
- ash/src/extensions/ext/debug_marker.rs
- ash/src/extensions/ext/debug_utils.rs
- ash/src/extensions/khr/acceleration_structure.rs
- ash/src/extensions/khr/timeline_semaphore.rs
- ash/src/extensions/nv/ray_tracing.rs
- ash/src/instance.rs
- ash/src/prelude.rs
this is a breaking change
see https://github.com/MaikKlein/ash/pull/493
> remove From<vk::Result> for VkResult

- generator/src/lib.rs
Some clippy lint long ago apparently suggested to explicitly specify a type for all random generators in 8550683 ("Address all the clippy lints (#233)"), so the `impl BuildHasher` trait was apparently passed as a placeholder for the `RandomState` default that's selected.
This does not serve any purpose and that (likely bogus) clippy warning no longer shows up, making it safe to remove the trait.
> generator: Remove unnecessary `impl BuildHasher` from HashMap types

- .github/workflows/ci.yml
- ash/src/entry.rs
Experimentally verified that this works as intended.
> Cover all features with clippy

- Changelog.md
We should probably come up with a PR template using checkmarks - bit of an annoying barrier IMO, but I keep forgetting to even document my own contributions.  Much easier to do them up-front than to come up with this in hindsight.
> changelog: Add entries for recent PRs #533, #537, #542

- generator/src/lib.rs
Much like `platform_types.rs` and `vk.rs` before, there is no need to generate this file as its contents are completely static.  This allows direct editing of the file without realizing that a copy lives in the generator - and will overwrite `macros.rs` when the generator is being run.
CC #549 which updated this file without changing the generator.
> generator: Exclude static macro code (`macros.rs`) from the generator

- generator/src/lib.rs
This has a bunch of minor iterator-related spot refactors, primarily to reduce nesting of iterators.
> Iterator simplification

- generator/src/lib.rs
`_` as prefix is intended for unused variables and bindings; it should be used in suffix position when intending to prevent a clash with a keyword instead.
> generator: Use `_` as suffix instead of prefix to mask keywords

- ash/src/device.rs
CC @lilly-lizard
Phone screens may be poor for reviewing code, but this was silly and sloppy.
> device: Correct #717 `reqirements` typo

- Changelog.md
- ash/src/vk.rs
This is related to a comment I made: https://github.com/ash-rs/ash/issues/573#issuecomment-1272222609
> Add `Handle::is_null()`

- Changelog.md
- ash/src/extensions/amd/buffer_marker.rs
- ash/src/extensions/amd/mod.rs
- ash/src/extensions/mod.rs
> extensions/amd: Add VK_AMD_buffer_marker

- Changelog.md
- ash/src/device.rs
- ash/src/extensions/nv/low_latency2.rs
- ash/src/extensions/nv/mod.rs
> extensions/nv: Add VK_NV_low_latency2 extension

- Changelog.md
- ash/src/extensions/khr/maintenance6.rs
- ash/src/extensions/khr/mod.rs
- ash/src/extensions/khr/push_descriptor.rs
> extensions/khr: Add VK_KHR_maintenance6

- Changelog.md
- ash/src/extensions/nv/copy_memory_indirect.rs
- ash/src/extensions/nv/mod.rs
> extensions/nv: Add VK_NV_copy_memory_indirect extension
