- src/lib.rs
Required for `corell` PR: https://github.com/gfx-rs/gfx/pull/1125/files#diff-54114f75674de7fb48ec86d044cbc150R40
> Export LoadingError from entry module

- src/device.rs
- Add `clear_color_image` command
- Add `dispatch` command
- Fix vertex buffer binding, fixes #10 
- Fix graphics pipeline creation for multiple pipelines. (Return pipelines *and* error on failure to recover the correctly built pipelines)
> Add some commands and fix graphics pipeline creation

- ash/src/lib.rs
Shouldn't this be exposed publicly, since it's used in the public `Entry::create_instance`?
> Expose InstanceError

- ash/src/device.rs
- ash/src/vk.rs
* Add commands for indirect draw/dispatch, next subpass and setting ref values
* Derive Eq for `Extent3D`
(version update not needed atm)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/25)
> Add a few new commands

- ash/src/util.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/45)
> Fix typo in util::Align documentation

- examples/Cargo.toml
- examples/src/lib.rs
The upgrade to winapi 0.3.x turned out to be super easy, and changing to winit 0.11 didn't appear to break anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/49)
> Update examples to winapi 0.3 and winit 0.11; clean up dead code

- ash/src/device.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
(Sorry for opening the previous issue, didn't realize it would be this simple to fix)
Adds the `first_scissor` parameter that was previously missing from `DeviceV1_0` and update the examples to reflect that. Next version bump should be 0.19.0 since this is breaking, naturally.
Resolves #57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/58)
> Add first_scissor to cmd_set_scissor

- examples/src/lib.rs
Vulkan 1.1 §33.3:
> The application should always return VK_FALSE. The VK_TRUE value is reserved for
use in layer development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/66)
> Fix example debug callback return value

- README.md
- ash/src/entry.rs
- examples/Cargo.toml
- examples/src/lib.rs
Basically, fixes #51 and brings in some of the kind of the macOS specific doohickeys needed to get a surface to draw on when using MoltenVK. The examples now work on macOS out of the box (after installing the LunarG SDK) 🎉
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/69)
> Make examples work on macOS using LunarG SDK

- ash/src/vk.rs
- generator/src/lib.rs
Closes #72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/90)
> Use repr(transparent) where possible and apply rustfmt to those files

- ash/src/extensions/debug_utils.rs
- ash/src/extensions/mod.rs
- ash/src/vk.rs
- generator/src/lib.rs
This implements the abstractions discussed in https://github.com/MaikKlein/ash/issues/70 to allow conversion of handles to/from `u64` and easy access of handle types.
I ran into a few interesting questions:
- Should the names of methods on extension objects (and even fields on their pointer tables) include the extension suffix? They're already disambiguated by being on the extension object, and a similar argument was used to remove suffixes from constants.
- When a rustier but less trivial interface can be written for a function (compare `set_object_name` vs `debug_utils_set_object_name_ext` here), should it exist alongside the naive wrapping, or replace it outright? If they both exist, what naming convention should be used?
---
This change is [<img …
> Handle trait, VK_EXT_debug_utils

- ash/src/vk.rs
- ash/tests/display.rs
- generator/src/lib.rs
Inspired by people doing unpleasant things with `mem::transmute` in debug callbacks.
I fixed up the `Error` and `Display` impls for `vk::Result` to match convention/be more helpful while I was in there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/99)
> impl Display for constants

- ash/src/vk.rs
- generator/src/lib.rs
This enables ash code to better interoperate with non-ash based vulkan code, including but not limited to foreign libraries such as SteamVR. I gather that it may also permit gfx-hal to substantially reduce use of `transmute`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/101)
> Expose conversions between enums and raw values

- ash/src/version.rs
While the traits for Instance / Device 1_1 were added, they were not visible outside of the crate (they are public in the modules `instance` and `device`, but those modules themselves are private).
This pull request re-exports them in the `version` module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/107)
> Export Vulkan 1.1 traits

- ash/src/vk.rs
- generator/src/lib.rs
Fixes strange behavior if a Vulkan flags constant setting multiple bits is defined prior to that which sets only one of those bits. This could lead to the combined constant's name being shown when it shouldn't be.
This is only a theoretical bug: most flags constants are one bit, and multi-bit special cases tend to be the last. Still, better to be safe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/102)
> More robust Display for flags types

- ash/src/entry.rs
- ash/src/instance.rs
- ash/src/version.rs
- ash/src/vk.rs
- generator/src/lib.rs
`enumerate_instance_version` is a function meant to be called before instance creation. This pull request moves its function pointer to `Entry`.
~~Also adds the `EntryV1_1` trait. I have not added any other functions to the trait yet, so as per [this comment](https://github.com/MaikKlein/ash/issues/52#issuecomment-412281719) it is not currently possible to create a 1.1 instance safely.~~
Nevermind, I tested this and it works. The issue mentioned in the comment is fixed now. Ash now basically has Vulkan 1.1 support, although there still are some issues remaining.
**Note**: ~~do we want this function to be marked as `unsafe`? It seems pretty safe to me.~~
It's been made safe.
Fixes #103.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Make `enumerate_instance_version` an `Entry` function

- ash/src/vk.rs
- generator/src/lib.rs
Set pointers in Default implementation fo structs to std::ptr::null()/null_mut() instead of zeroed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/110)
> Default trait: set pointers to std::ptr::null()/null_mut()

- ash/src/instance.rs
As discussed in #109, the various getter functions for physical device don't work, because the user isn't able to pass in a chain of mutable structures for the Vulkan driver to fill in.
- All getters will probably have to be marked `unsafe`, since we cannot validate the user passed in a structure with a valid `p_next` pointer.
- I have not touched the getters which don't have any extensions yet. For example, I haven't modified `get_physical_device_external_fence_properties` since there are no published extensions which affect it (yet).
- I don't know how to solve the issue with functions which need to work with vectors, specifically `get_physical_device_queue_family_properties2`, which does have an extension structure for it (`QueueFamilyCheckpointPropertiesNV`).
- We would have to …
> Fix instance getters to support extensions

- ash/Cargo.toml
- ash/src/allocator.rs
- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/surface.rs
- ash/src/extensions/swapchain.rs
- ash/src/instance.rs
- ash/src/lib.rs
- ash/src/util.rs
- ash/src/vk.rs
- examples/src/bin/texture.rs
- examples/src/lib.rs
- generator/src/lib.rs
I tried using the `vk_version_{*}` macros, but they didn't work: 
```
cannot find type `uint32_t` in this scope`
```
This pull request fixes them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/114)
> Use Rust integral types

- examples/Cargo.toml
- examples/src/lib.rs
The surface creation code expects `hinstance` to be the handle of the process with created the window. For some reason, in the example we were passing in a handle to the top level window.
The `HINSTANCE` parameter isn't really used for anything on modern Windows, and even the validation layers will gladly accept invalid values, but the example should be technically correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/118)
> Fix Windows surface creation in the example

- ash/src/vk.rs
- examples/src/lib.rs
- generator/src/lib.rs
Fixes #112
This is a relatively conservative approach; rather than inventing stub functions or trying to guess which functions are nullable in practice, we're just replicating the mundane C semantics, as is done most other places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/128)
> Wrap function pointers in Option since they might be null

- ash/src/vk.rs
- examples/src/lib.rs
- generator/src/lib.rs
Improves consistency with other newtypes and with bitflags and allows construction of statically unknown flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/122)
> More consistent names in flags API

- examples/src/lib.rs
The changes for Ash 0.25 resulted in the macOS demo to fail compilation. There is a new runtime loader issue that still remains, which I will open a new issue for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/147)
> Compile fixes for macOS

- ash/src/entry.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/151)
> Fix macOS instance loading - use libvulkan.dylib instead of libMoltenVK.dylib so that loader is not bypassed

- README.md
- Dedicated section for strongly typed handles
- Extended discussion of builder safety
@rhzk brought to my attention that it's easy for people coming from C/C++ to miss the `T::null()` pattern.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/159)
> Clarify some patterns in the README

- ash/src/vk.rs
- generator/src/lib.rs
This PR corresponds to https://github.com/MaikKlein/ash/issues/141.
Current implementation:
- Each builder creates a trait ex.: ```ApplicationInfoBuilder``` -> ```pub trait ApplicationInfoBuilderNext```
- Structs implementing this trait are then taken in the builder's next function
- Each struct then makes a bunch of impls for the traits based on the ```extends``` attribute provided in vk.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/146)
> Builder next

- ash/src/vk.rs
- generator/src/lib.rs
Where `Foo` extends `Bar`, `BarNext` was implemented for `FooNext` instead of `Foo`. I also adjusted the naming to read naturally.
> Fix builder next methods

- ash/src/device.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maikklein/ash/166)
> Add get_pipeline_cache_data

- ash/src/vk.rs
- generator/src/lib.rs
Fix https://github.com/MaikKlein/ash/issues/155. There is a lot of noise because I already used 1.0.0 stable version of rustfmt. 
Probably merge the https://github.com/MaikKlein/ash/pull/171 first and I'll rebase then.
> Builder: fix &'a [c_void] to &'a [8u]

- ash/Cargo.toml
`shared_library` uses a flexible "`1`" for its `lazy_static` lib. By following suit, `ash` can avoid duplicate versions of `lazy_static` in transient dependencies builds.
I tested this by building `ash`: everything built fine.
> Update `lazy_static` version to match `shared_library`'s

- generator/src/lib.rs
`CStr::from_ptr` takes a `*const c_char`, which is not synonymous with `*const i8`. On ARM in particular, `c_char` is unsigned.
> Fix build on ARM

- ash/src/vk.rs
- generator/src/lib.rs
Adds extension names to the function pointer structs.
`vk::KhrSwapchain::name()`
Currently Rust doesn't support `CStr` as associated consts, so functions have to be used for now.
> Generate extension names

- ash/src/extensions/experimental/amd.rs
- ash/src/extensions/experimental/mod.rs
- ash/src/extensions/mod.rs
- ash/src/lib.rs
Addresses https://github.com/MaikKlein/ash/issues/178#issuecomment-457942089
Not fully supports all parts of the APIs, just trying to get some general feedback if this meets the expected structuring.
> Experimental AMD extensions

- ash/src/device.rs
- ash/src/vk.rs
- generator/src/lib.rs
Note: this is a breaking change!
Some related reading: https://lkml.org/lkml/2015/9/3/428
This has been plaguing WebRender on gfx-rs port running Windows/Vulkan.
> Pass constant size arrays by reference

- ash/src/vk.rs
- ash/tests/constant_size_arrays.rs
- generator/src/lib.rs
PR #191 introduced a bug into the generator where constant sized array struct fields were generated as slices. This PR adds a flag to `type_tokens` that will revert that behavior while still generating FFI function signatures with pointers instead of fixed sized arrays (e.g. for `set_blend_constants`).
In addition, all instances of `HashMap` and `HashSet` have been replaced with `BTreeMap` and `BTreeSet`, which makes the generation of `vk.rs` idempotent for the same `vk.xml` input. This should obviate the need for #130 and make it much easier to see how changes to the generator or `vk.xml` affect the generated output.
> Fix struct generation with constant size arrays

- ash/src/extensions/experimental/amd.rs
- ash/src/vk.rs
- ash/tests/display.rs
- generator/src/lib.rs
Improves consistency with Rust idioms. In particular, readability of panic messages arising from unwrapped `VkResult`s is vastly improved.
> Idiomatic Debug impls for enums and bitflags

- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
The memory types may vary between different versions of MoltenVK.
This solution just changes all the memory request flags to both `HOST_VISIBLE` and `HOST_COHERENT` to fix the delay of memory data transfer.
> Fix black screen for examples on macOS platform

- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
Load the example shader and texture files with `include_bytes!` so that they can be run from the root project directory. Previously, `cargn run --bin <EXAMPLE>` could only be run from the `examples` directory.
> Fix shader and texture data loading in examples

- ash/src/extensions/ext/debug_marker.rs
- ash/src/extensions/ext/debug_report.rs
- ash/src/extensions/ext/debug_utils.rs
- ash/src/extensions/khr/android_surface.rs
- ash/src/extensions/khr/display_swapchain.rs
- ash/src/extensions/khr/surface.rs
- ash/src/extensions/khr/swapchain.rs
- ash/src/extensions/khr/wayland_surface.rs
- ash/src/extensions/khr/win32_surface.rs
- ash/src/extensions/khr/xcb_surface.rs
- ash/src/extensions/khr/xlib_surface.rs
- ash/src/extensions/mvk/ios_surface.rs
- ash/src/extensions/mvk/macos_surface.rs
- ash/src/extensions/nv/mesh_shader.rs
- ash/src/extensions/nv/ray_tracing.rs
Disclaimer: This pull request is not ready to be merged into master. This is a proposal for an interface addition
So in order to remedy issue #226, I've made this pull request. I've implemented an interface proposal for `ash::extensions::khr::Surface` and `ash::extensions::khr::Swapchain` as example code that needs to be reviewed.
The idea is to add a `raw_fp()` function to every extension struct (i.e Surface) that returns a non-mutable reference to the inner structure that holds the function pointer(s). In the case of Surface, this is the `ash::vk::KhrSurfaceFn` struct.
Additonally, we could also add `instance_handle()` and `device_handle()` functions where applicable, since the structures that hold these handles, have grabbed the function pointers specifically for those handles.
Example …
> Expose raw function pointers in extensions

- ash/src/extensions/khr/display.rs
- ash/src/extensions/khr/mod.rs
Quick attempt at adding direct-to-display rendering support—heavily based on the already provided extensions.
- Other extensions allowed dead code. I wasn't sure if that's necessary here.
- `Display` presumably does not clash with any other structs in the codebase?
> Add `VK_KHR_display` extension support

- ash/src/device.rs
Makes it easier not to ignore actual errors.
Fixes #242.
> Return `VkResult<bool>` from get_fence_status

- ash/src/vk.rs
- generator/src/lib.rs
Adds equality-related traits to VkClearRect, VkOffset2D, VkOffset3D,
VkRect2D and VkSurfaceFormatKHR. Fixes a typo preventing said traits
from being applied to VkExtent2D.
> Make more structs derive PartialEq/Eq/Hash

- ash/src/extensions/khr/push_descriptor.rs
The `vkspec.html` page is rather large and slow to load and navigate. This change is consistent with all other doc links.
> Use the individual man page doc links for the push_descriptor extension

- README.md
- ash/src/vk.rs
- generator/Cargo.toml
- generator/src/lib.rs
Remaining work:
```
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES = 49,
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES = 50,
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES = 51,
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES = 52,
```
The above associated types are not generated.
Fixes #263
> Vulkan 1.2 Support

- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/ext/debug_marker.rs
- ash/src/extensions/ext/debug_report.rs
- ash/src/extensions/ext/debug_utils.rs
- ash/src/extensions/khr/android_surface.rs
- ash/src/extensions/khr/display.rs
- ash/src/extensions/khr/display_swapchain.rs
- ash/src/extensions/khr/push_descriptor.rs
- ash/src/extensions/khr/surface.rs
- ash/src/extensions/khr/swapchain.rs
- ash/src/extensions/khr/wayland_surface.rs
- ash/src/extensions/khr/win32_surface.rs
- ash/src/extensions/khr/xcb_surface.rs
- ash/src/extensions/khr/xlib_surface.rs
- ash/src/extensions/mvk/ios_surface.rs
- ash/src/extensions/mvk/macos_surface.rs
- ash/src/extensions/nv/mesh_shader.rs
- ash/src/extensions/nv/ray_tracing.rs
- ash/src/instance.rs
- ash/src/lib.rs
- ash/src/version.rs
This PR adds high level Vulkan 1.2 wrappers for `Entry`, `Instance` and `Device`. I also updated the doc links, added the missing `InstanceV1_1::get_physical_device_features2` function (fixes https://github.com/MaikKlein/ash/issues/258) and implemented `EntryV1_1` with accompanying note (fixes https://github.com/MaikKlein/ash/issues/254).
> Add high level wrappers for Vulkan 1.2

- examples/Cargo.toml
- examples/src/lib.rs
While trying to build the examples on osx I would get the following error:
```
error[E0282]: type annotations needed
--> /Users/plot/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.13.0/src/appkit.rs:3418:9
|
3418 |         msg_send![self, setStringValue:label];
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ consider giving `result` a type
|
= note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
After making the changes in this PR I was able to build the examples on osx and run the bin.
> fix build errors for examples on osx

- ash/src/extensions/khr/external_memory_fd.rs
- ash/src/extensions/khr/mod.rs
This is my go at adding support for the `VK_KHR_external_memory_fd` extension. There are a couple things I'm unsure about though:
1. That this is a necessary addition. Is the end goal of ash to have all possible extensions supported this way?
2. The storing of the device handle in the extension struct. I suppose this is because it's a device specific extension, so it's only guaranteed to work with with the device it was created with.
3. The specificity of this extension to unix. As far as I know, file descriptors are unique to unix alone, so it makes sense to put this extension behind a unix feature flag.
> Add `VK_KHR_external_memory_fd` extension support

- ash/src/entry.rs
- ash/src/instance.rs
This PR is the result of the fact that as a new user of this library, it caught me off guard that I wasn't able to drop `Entry` after successfully creating an `Instance`.
It adds documentation to specify these invariants which the caller must uphold when creating `Device`s and `Instance`s.
Closes #271
One caveat to this, I am currently under the impression that the entry, instance, and device traits are maintained by hand, and are not auto-generated. If that is incorrect, then likely this PR only includes edits to auto-generated code, which likely isn't desirable, and I'll happily close the PR without it merging, since this interaction *is* documented in the README.
> Add a Safety section to the documentation of create_instance and create_device

- ash/src/entry.rs
- ash/src/instance.rs
Minor adjustment to how the doc links are rendered with the new safety sections.
See here for example:
https://github.com/MaikKlein/ash/pull/272#discussion_r386053611
> Adjust doc link rendering with safety sections

- ash/Cargo.toml
- ash/src/entry.rs
This switches the symbol loading from `shared_library` to `libloading` because `shared_library` is not *really* maintained (see https://github.com/tomaka/shared_library/issues/6#issuecomment-264773459 for example).
One noticeable benefit this brings is that it provides a fix for #251. Note that the examples currently require the `VK_EXT_debug_report` extension and therefore won't work on wine without changes.
So: fixes #251
> Switch to `libloading`

- ash/src/vk.rs
- generator/Cargo.toml
- generator/src/lib.rs
Ash still uses vkxml in some parts which is not aware of command aliases, and therefore we had a few extensions that were just empty.
So instead of upgrading ash to vk_parse everywhere, this PR just uses the alias information of vk_parse as a workaround.
This should fix 3 open PRs
https://github.com/MaikKlein/ash/pull/278
https://github.com/MaikKlein/ash/pull/276
https://github.com/MaikKlein/ash/pull/262
> Fix incorrect generation of commands with aliases

- Changelog.md
- ash/src/device.rs
Some functions incorrectly had a `vk::Device` as a param. Sadly this slipped into the 0.30.0 release
> Remove incorrect device params

- ash/src/vk.rs
- generator/src/lib.rs
Bitflag "enums" currently have both `as_raw` and `from_raw` functions with `const` qualifiers. I don't see any reason why enums shouldn't as well.
This would allow creating custom enums that are subsets of, or intersect with vk enums "safely":
```
#[repr(i32)]
enum Foo {
A = ash::vk::DescriptorType::SAMPLER.as_raw(),
B = ash::vk::DescriptorType::COMBINED_IMAGE_SAMPLER.as_raw()
}
```
> Add const qualifier to `as_raw` and `from_raw` fns on enums

- ash/src/extensions/khr/ray_tracing.rs
[`MemoryRequirements2`](https://docs.rs/ash/0.30.0/ash/vk/struct.MemoryRequirements2.html) has a `sType` field, which should not be zero-initialized because it results in a invalid instance. I looked through some more usages of `mem::zeroed` and this seems like the only wrong one.
Fixes #293 (I don't have hardware that supports this extension but this should fix it)
> Initialize MemoryRequirements2 with `Default`

- ash/Cargo.toml
- ash/src/entry.rs
Based on #291 
This pull request moves lib creation out of `new_custom`, which allows `new_custom` to not return a `Result`, also giving the user the control over Library creation error handling.
> Move lib creation out of `EntryCustom::new_custom`

- ash/Cargo.toml
- ash/src/entry.rs
- ash/src/entry_libloading.rs
- ash/src/lib.rs
This builds on #292 to make `libloading` optional, but still used by default.
> Make libloading an optional dependency

- ash/src/extensions/ext/mod.rs
The [DebugMarker](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_debug_marker.html#_deprecation_state) and [DebugReport](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_debug_report.html#_deprecation_state) extensions in Vulkan have been deprecated and replaced by the unified DebugUtils extension, as announced in this [LunarG document [PDF]](https://www.lunarg.com/wp-content/uploads/2018/05/Vulkan-Debug-Utils_05_18_v1.pdf).
I used the DebugMarker module and experienced a crash on Ubuntu 20.04 on an Ice Lake CPU + GPU.
This PR adds this deprecation to the crate documentation, and points users to the documentation for the replacement DebugUtils extension.
> Deprecate the DebugMarker and DebugReport extension modules

- ash/src/entry_libloading.rs
It is in some cases necessary to load a specific Vulkan dll/so with a different name and/or from a different location. Instead of copying this function to a downstream project (and making the `LoadingError` constructor public to retain the same interface), split `Entry::new()` such that downstream projects can easily specify and use an alternate Vulkan implementation.
> Provide Vulkan library loader from custom path

- README.md
crates.io does the syntax coloration only when the word `rust` is written in lowercase.
For example [https://crates.io/crates/debug_print](https://crates.io/crates/debug_print): 
in the [README.md](https://github.com/RustyNixieTube/debug_print/blob/master/README.md) rust is written in lowercase and then in [crates.io](https://crates.io/crates/debug_print) the syntax coloration appears.
but in your [README.md](https://github.com/MaikKlein/ash/blob/master/README.md) `Rust` is written an with uppercase R and syntax coloration doesn't appear in your [crates.io](https://crates.io/crates/ash).
> Correction of the language name in README.md

- .github/workflows/ci.yml
- ash-window/examples/winit.rs
- ash/tests/constant_size_arrays.rs
- generator/src/lib.rs
This allows me to use my beloved `clippy --workspace --all-targets` without noise from leftover issues :slightly_smiling_face:
> [CI] Test/check/lint all targets, fixup leftover clippy warnings

- ash/src/vk/definitions.rs
- ash/src/vk/extensions.rs
- generator/src/lib.rs
We need to retrieve the header version and extension spec versions `ash` was compiled against. This includes some ugly magic to rework `vk.xml` C-macros (:disappointed:).
Please see inline `TODO`s for areas open to improvement before merging.
> Expose header version and extension spec version constants

- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
The examples (triangle and texture) wait for a fence immediately after submitting a command buffer. This is not a good practice for performance. I moved the wait until the command buffer is reused (one frame later).
Measured average frame times on Intel i7-1065g7 (4K display, 200% scaling).
**Triangle sample:**
Old = 3.5ms
New = 2.4ms
**Texture sample:**
Old = 4.2ms
New = 3.0ms
> Optimized example fences. Waited immediately. Now waits before reuse (next frame)

- examples/src/lib.rs
According to specs for vkGetPhysicalDeviceSurfaceFormatsKHR(), at least
one surface format must be returned, and returned formats must not be
VK_FORMAT_UNDEFINED.
> Simplify example surface format selection

- examples/src/lib.rs
Hopefully this will make it easier to understand `find_memorytype_index()`:
* I find it harder to reason about loops that write to variables they read from, so this avoids repeatedly updating `memory_type_bits` in favor of making the relationship between `index` and `memory_req.memory_type_bits` more explicit.
* This has merged `find_memorytype_index_f()` into `find_memorytype_index()` to reduce the amount of jumping around needed to understand what's going on.
~Unfortunately, this _does_ come with a behavior change: If an exactly matching memory type cannot be found, this now returns the last acceptable memory type, whereas it previously returned the first.~
> Simplify example memory selection

- examples/src/lib.rs
The example code originally checked all 32 memory types even if the instance returned fewer memory types.
> Only scan memory_type_count memory types in examples

- ash/src/device.rs
the stride can be bigger than a u64
for example when querying more than one pipeline statistic
> remove erroneous assert in get_query_pool_results

- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/ext/debug_marker.rs
- ash/src/extensions/ext/debug_report.rs
- ash/src/extensions/ext/debug_utils.rs
- ash/src/extensions/ext/metal_surface.rs
- ash/src/extensions/ext/tooling_info.rs
- ash/src/extensions/khr/android_surface.rs
- ash/src/extensions/khr/display.rs
- ash/src/extensions/khr/display_swapchain.rs
- ash/src/extensions/khr/external_memory_fd.rs
- ash/src/extensions/khr/pipeline_executable_properties.rs
- ash/src/extensions/khr/ray_tracing.rs
- ash/src/extensions/khr/surface.rs
- ash/src/extensions/khr/swapchain.rs
- ash/src/extensions/khr/timeline_semaphore.rs
- ash/src/extensions/khr/wayland_surface.rs
- ash/src/extensions/khr/win32_surface.rs
- ash/src/extensions/khr/xcb_surface.rs
- ash/src/extensions/khr/xlib_surface.rs
- ash/src/extensions/mvk/ios_surface.rs
- ash/src/extensions/mvk/macos_surface.rs
- ash/src/extensions/nv/ray_tracing.rs
- ash/src/instance.rs
- ash/src/prelude.rs
- ash/src/vk.rs
- ash/src/vk/definitions.rs
- ash/src/vk/enums.rs
- generator/Cargo.toml
- generator/src/lib.rs
Hi Maik,
Apologies for this massive PR. It's some upfront cleanup work that came up while working on `ash`, in particular around `Result` types and error handling.
I can only recommend to review the changes per commit to get around the bulk of it easily. While this aims to make the code ever so slightly better it results in lots of noise, let me know if any commit (hash) is not worth taking in and I'll gladly remove it again.
To highlight the changes:
- Make sure all results are checked with `#[must_use]` on `vk::Result`;
- Conversion helpers from `vk::Result` to `Result<T, vk::Result>`;
- Clippy fixes;
- Simplifications in the generator around array code handling;
- Parsing some C expressions into `TokenStream` and replacing identifiers with their Rust counterpart. This is going to be …
> Preliminary cleanup pass

- ash/src/extensions/khr/acceleration_structure.rs
I was working with `ash::extensions::khr::AccelerationStructure` and noticed one method was missing the docs link!
Cheers!
> Add missing doc link in AccelerationStructure

- ash/src/extensions/khr/deferred_host_operations.rs
- ash/src/extensions/khr/mod.rs
The [`VK_KHR_deferred_host_operations` extension](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_deferred_host_operations.html) is used by `VK_KHR_acceleration_structure` to request deferral for host operations and thus can be useful for optimizing ray tracing programs.
I tried to match the style of other extensions, but please let me know if I should make any changes!
> Add `VK_KHR_deferred_host_operations` extension support.

- ash/src/vk/extensions.rs
- ash/src/vk/features.rs
- generator/src/lib.rs
In rust references to DSTs (Dynamically Sized Types) like slices and
trait objects are 16-bytes instead of 8 (leaking into the next parameter
of a function call). The static-sized array generated here has its size
known beforehand and will not suffer from this issue [1], but might be
confusing for future readers/authors: convert it to a raw pointer just
to be safe.
[1]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=88acb9736455f7262ecf4af2077f3a59
---
See https://github.com/MaikKlein/ash/pull/352#issuecomment-753475214 as well :)
> Use raw pointers to static-sized arrays in FFI signatures

- ash/src/vk/definitions.rs
- ash/src/vk/extensions.rs
- ash/src/vk/features.rs
- generator/src/lib.rs
Fixes https://github.com/MaikKlein/ash/issues/360
`c_void` is not the same as Rust's void type, `()`, making function
pointers like `PFN_vkFreeFunction` pretty much impossible to implement
without casting. Instead of just turning this into `-> ()`, remove the
return type altogether, and add some asserts to prevent types of this
kind from being accidentally generated.
> generator: Turn c_void-returning functions into Rust ()

- ash/Cargo.toml
- ash/src/entry_libloading.rs
This new version marks `Library::new` as unsafe, because loading a library invokes the libraries' entrypoint which may or may not have certain preconditions and perform unsafe/undefined operations, just like any other native function loaded through `libloading`.
---
Not sure if we should wrap this in `unsafe` or mark the entire `fn with_library` as unsafe, just like all other Vulkan functions?
> ash: Update libloading from 0.6 to 0.7

- ash/src/extensions/khr/acceleration_structure.rs
- ash/src/extensions/khr/ray_tracing_pipeline.rs
This handle is already held onto when creating the safe wrapper object, but is inconsistently required again in some but not all functions.  Remove it from every function and use the internal handle instead.
Closes: #377
Fixes: 05747b2 ("Update Vulkan-Headers to 1.2.162 with stable ray-tracing spec (#341)")
---
_Yet another_ porting artifact of the stable KHR RT bindings...
> Remove device argument from acceleration structure and RT pipeline fns

- ash/src/vk/extensions.rs
- ash/src/vk/features.rs
- generator/src/lib.rs
CString::new needs to perform an allocation to own the `&'static str` and append a NULL byte to it. We can instead perform this "allocation" in the generator and emit a byte-string literal with trailing NULL byte that can immediately be used by the function loader.
---
~~Note this is just a local test I wrote up. Not sure if it should go in but~~ It might be beneficial towards all the embedded questions/issues where such allocations are out of the question.
> Remove unnecessary CString allocation when loading functions

- ash/src/extensions/khr/acceleration_structure.rs
Came across the original PR introducing headers 1.2.162 with the official KHR RayTracing spec, and found a slightly related comment (https://github.com/MaikKlein/ash/pull/341#discussion_r541967759) about unfortunate casts that could have been safe transmutes because references to PODs have the same size as raw pointers. Turns out these shouldn't be normal pointers but slices (fat pointers) :anguished: 
In addition this PR introduces extra asserts: we're exposing a "safe" (still marked `unsafe` though, just type reinterpretation) layer that should at the very least validate the length of this and other nested arrays.
> Fix safe CmdBuildAccelerationStructuresIndirect signature and add extra length validation

- README.md
It isn't too uncommon to pass a single builder element into another builder, and `slice::from_ref` fits perfectly while preserving lifetime of the builder without calling `.build()`. We have used this successfully in our codebase to uncover and prevent numerous use-after-free bugs, and thought it's worth to share on the front page.
> README: Add lifetime-preserving builder example using slice::from_ref

- ash/src/vk/bitflags.rs
- ash/src/vk/const_debugs.rs
- ash/src/vk/extensions.rs
- generator/src/lib.rs
Constants (enumeration bitflags) containing the word `external` were not stripped of their common typename, and quick debugging showed the word `VKTERNAL_...` in `struct_name`. `_EXT` would be the first extension to match in `VK_EXTERNAL_...` messing up `struct_name` with a global `.replace`, in turn not removing it from the variant name.
> generator: Only expect vendor name at the end of constants

- ash/src/entry_libloading.rs
Fixes #388
All type parameters are implicitly bound by Sized; matching the `&` out of `&str` implies that `str` must be bound by `Sized` which is not true, resulting in:
18 |         let entry = ash::Entry::with_library("foo")?;
|                                              ^^^^^ doesn't have a size known at compile-time
|
::: /home/marijn/Code/TraverseResearch/ash/ash/src/entry_libloading.rs:73:39
|
73 |     pub unsafe fn with_library(path: &impl AsRef<OsStr>) -> Result<Entry, LoadingError> {
|                                       ----------------- required by this bound in `ash::entry_libloading::<impl EntryCustom<Arc<libloading::Library>>>::with_library`
After all `Library::new` accepts an `impl AsRef<OsStr>` without borrow, which is what this function is modeled after to pass the …
> entry_libloading: Do not pass AsRef implementation by reference

- ash/src/extensions/khr/external_memory_fd.rs
`MemoryFdPropertiesKHR` is a struct that, despite being used as output, hsa to be initialized properly with a valid `sType` set, otherwise:
Validation Error: [ VUID-VkMemoryFdPropertiesKHR-sType-sType ] Object 0: handle = 0x7f035464d648, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xdc6b3a0d | vkGetMemoryFdPropertiesKHR: parameter pMemoryFdProperties->sType must be VK_STRUCTURE_TYPE_MEMORY_FD_PROPERTIES_KHR. The Vulkan spec states: sType must be VK_STRUCTURE_TYPE_MEMORY_FD_PROPERTIES_KHR (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkMemoryFdPropertiesKHR-sType-sType)
> external_memory_fd: Initialize output struct with proper sType

- .github/workflows/ci.yml
Make sure the submodule hash, state of the generator and resulting source files in ash are in sync for every submission.
> ci: Run the generator and fail if output is different

- .github/workflows/ci.yml
- ash/src/entry.rs
- ash/src/entry_libloading.rs
- ash/src/lib.rs
Unfortunately docs are not explicitly (build-)tested as part of `--all-targets` allowing broken code to slip in as shown by #390.
Also remove the `rust` listing type which is the default, leaving only `no_run` (until the CI has a loadable Vulkan library).
> ci: Test docs in addition to `cargo t --all-targets`

- ash/src/extensions/mvk/ios_surface.rs
- ash/src/extensions/mvk/macos_surface.rs
Per the discussion at #398, this brings these names in line with the other extensions, which lack the suffix.
> Remove the _mvk suffix from the two extensions' functions

- ash/src/extensions/ext/buffer_device_address.rs
- ash/src/extensions/ext/mod.rs
- ash/src/extensions/khr/buffer_device_address.rs
- ash/src/extensions/khr/mod.rs
This extension comes in both a KHR and an EXT version, so I included them both for completeness.
> Add VK_KHR/EXT_buffer_device_address extension

- ash/src/device.rs
This adds `merge_pipeline_caches`, `queue_bind_sparse` and `get_render_area_granularity` to the `DeviceV1_0` trait. I hope I didn't accidentally edit an autogenerated file again.
> Add 3 missing DeviceV1_0 functions

- ash/src/extensions/mod.rs
- ash/src/extensions/nn/mod.rs
- ash/src/extensions/nn/vi_surface.rs
I followed the examples of other surface extensions for this one, so hopefully it's good as-is. I was not sure whether the function names should have `_nn` at the end or not. `create_xlib_surface` doesn't end in `_khr` but `create_mac_os_surface_mvk` does have the `_mvk`. My own preference would be without the suffix, since it's already implicit in the module and struct name.
> Add VK_NN_vi_surface extension

- ash/src/lib.rs
With 1.51 upper case acronyms are not allowed by default in clippy. Lets temporarily disable the lint.
> Allow upper case acronyms for now

- ash/src/extensions/khr/create_render_pass2.rs
- ash/src/extensions/khr/mod.rs
This was made core in 1.2, but I can only use 1.1 so need to load the extension.
Extension doc:
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_create_renderpass2.html
> Add high-level extension wrapper for the 1.1 extension VK_KHR_create_renderpass2

- ash/src/vk/extensions.rs
- ash/src/vk/feature_extensions.rs
- generator/src/lib.rs
All enumeration aliases already extend the base type by being placed in its `impl` block. Use `Self::` instead of repeating the type name. DRY.
(Preparation for future cleanups relating to >.170 bringup)
> generator: Improve alias readability by using `Self::` as type

- ash/src/vk/definitions.rs
- generator/src/lib.rs
Do not Repeat Yourself in `impl` blocks, especially with the extra lifetime these are unnecessarily verbose.
> generator: Use `Self` as return type in builder functions

- ash/src/vk/bitflags.rs
- ash/src/vk/const_debugs.rs
- ash/src/vk/enums.rs
- generator/src/lib.rs
~Depends on #409~ merged already.
This change prepares for future additions in vk_parse fields ([1]) by converting over the enum generation path from vkxml.  Most of the conversion is easy by repurposing the existing `EnumSpec` parsing logic from extension constants for all enumeration variants, with slight modifications to not bail when `extends` is not set which is specific to extension constants.
As an (unintended) added bonus this unification of the `EnumSpec` codepath allows aliases (for backwards-compatible names) to be generated as discussed earlier in [2].
[1]: https://github.com/krolli/vk-parse/pull/17
[2]: https://github.com/MaikKlein/ash/pull/384#discussion_r588693967
---
@MaikKlein you're probably wondering by now why I'm not helping pushing generator2 over the finish line. …
> generator: Generate enums from vk_parse representation

- ash/src/vk/enums.rs
- generator/src/lib.rs
Previously, the `Display` impl for `vk::Result` did not include handling for extension values. For example, VK_ERROR_OUT_OF_DATE_KHR would display simply as "-1000001004".
With this change, we fall back to the `Debug` impl of the `Result` if the value is unknown (i.e. from an extension). This preserves the current nice messages for non-extension values, and the numeric output for truly unknown values, but displays the enum variant name (e.g. "ERROR_OUT_OF_DATE_KHR")  for extension-provided enum variants.
> Improve Result's Display impl for extension values

- ash/src/vk/enums.rs
- generator/src/lib.rs
The docs clearly state:
```rust
#[rustc_deprecated(since = "1.42.0", reason = "use the Display impl or to_string()")]
fn description(&self) -> &str {
"description() is deprecated; use Display"
}
```
We already have a `Display` implementation containing an identical `match` block and has further improvements on the way in [1].
[1]: https://github.com/MaikKlein/ash/pull/424
> generator: Remove deprecated `description()` impl for `Error`

- ash/src/device.rs
- ash/src/instance.rs
Closes #422.
Added missing functions to DeviceV1_0 and InstanceV1_0.
> added missing functions to V1_0 traits

- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/ext/full_screen_exclusive.rs
- ash/src/extensions/khr/get_memory_requirements2.rs
- ash/src/extensions/khr/get_physical_device_properties2.rs
- ash/src/extensions/khr/surface.rs
- ash/src/extensions/khr/swapchain.rs
- ash/src/instance.rs
Following our little discussion in [1] to just use `0` instead.
This also renames the remaining few `num` variables to `count` to more closely match the rest of the codebase and the name of the parameter in Vulkan [2].
[1]: https://github.com/MaikKlein/ash/pull/416#discussion_r604260529
[2]: https://github.com/MaikKlein/ash/pull/416#discussion_r604258864
> Do not initialize simple integer types with mem::zeroed()

- ash/src/vk/const_debugs.rs
- ash/src/vk/enums.rs
- generator/src/lib.rs
As brought up in [1] a new enum variant "pattern" not dealth with by our type-prefix stripper went silently unnoticed.  Explicitly listing the few misnamed enum variants and panicking otherwise makes sure this won't happen again.
[1]: https://github.com/MaikKlein/ash/pull/411#issuecomment-826013950
Also add `_INTEL` to the list of vendor suffixes to strip, cleaning more misnamed variants.
> generator: Fortify enum-variant type prefix stripping

- ash/src/vk/bitflags.rs
- ash/src/vk/const_debugs.rs
- ash/src/vk/definitions.rs
- ash/src/vk/extensions.rs
- generator/Cargo.toml
- generator/src/lib.rs
Depends on ~#409, #410~, https://github.com/krolli/vk-parse/pull/17
This is my initial take on upgrading to .170 and beyond (see also #403), unfortunately belated due to the extra changes needed to get the `bitwidth` field in `vk-parse` and refactor the generator to use `vk_parse::Enums`. Compared to #403 this approach uses the `num` crate instead of converting all debug numbers to 64-bit, though a better solution might be to simply duplicate the function in a 32- and 64-bit version. We'll have to see how and in what order to merge them, as this PR doesn't provide a safe wrapper for the `Synchronization2` extension either. I can rebase this on top if necessary.
> generator: Add support for vkFlags64 and update to 1.2.170

- ash/src/vk/platform_types.rs
Depends on #429
`()` is an empty tuple which can be constructed, while `ffi::c_void` cannot.  This is only ever used as an opaque pointer anyway and not used by Ash; those wishing to access members directly should cast it to a struct representation of choice (`winapi`, `windows-rs` or something custom).
Fixes #156
> vk/platform_types: Mark SECURITY_ATTRIBUTES as a true ffi::c_void

- ash/src/vk/definitions.rs
- generator/src/lib.rs
Fixes #256
As per #256 no explicit length field is available for `pSampleMask`, this is based on `ceil(rasterizationSamples/32)` instead.  It is valid to not set an array for `pSampleMask` (under normal circumestances this is signaled by setting the length to zero, and the array pointer is ignored) but this has to happen by setting the pointer to `NULL`.
EDIT: And so Erupt followed suit 😬 https://gitlab.com/Friz64/erupt/-/commit/5a0574a0f0c29330f15803dc0475c06bd88438c7 👀
> generator: pSampleMask setter should write NULL if slice is empty

- generator/src/lib.rs
I keep redoing these fixes, not realizing that they were already submitted as part of some other stale PR. It's about time to just get them in even if the benefit is minimal.
> generator: Small code cleanups

- ash/src/vk/extensions.rs
- ash/src/vk/features.rs
- generator/src/lib.rs
Depends on #439
Rusty wrappers are already marked `unsafe`, and by definition the raw Vulkan function pointers used under the hood are `unsafe` too.  Not needing `unsafe` when going directly through `self.fp_v1_x()` is odd at best.
> Mark all function pointer types as unsafe

- ash/src/vk/extensions.rs
- ash/src/vk/features.rs
- generator/src/lib.rs
~Depends on #439, #436~ Merged!
With function typedefs for commands having some elements filtered out (by name) if they were previously defined already, combined with unfiltered arrays containing the parameter sets and return type for _all_ commands expanded together in `quote!` macros the wrong array elements get combined resulting in incorrect signatures.  No-one seems to use function pointer types (but we should!) which is why this has gone unnoticed for some time.
> generator: Untangle mismatched parameter/return fn signatures in types

- ash/src/vk/definitions.rs
- ash/src/vk/macros.rs
- generator/src/lib.rs
Depends on #429 
With this PR I want to leverage existing parsing and generation infrastructure to completely automate the generation of define macros. It doesn't change much right now but will address #428 as if by magic when generating for `.175` :partying_face: 
Things we should discuss:
EDIT: This is now taken care of by a map, bit verbose but we do that for many other types too;
> generator: Parse and autogenerate version-related defines

- ash/src/vk/definitions.rs
- generator/src/lib.rs
Fixes https://github.com/MaikKlein/ash/issues/229
> Generate push_next function for all extended structs

- ash/src/vk/enums.rs
- examples/src/lib.rs
- generator/src/lib.rs
Using `cargo +nightly clippy --fix --all` on `clippy 0.1.56 (4927238 2021-07-29)`.
> Fix clippy lints on Rust 1.54 and beyond

- README.md
- ash-window/README.md
Draft to see how it renders.  Includes some typo fixes.
We'll have to work out how to bump `toml` crate dependency versions going forward; [`cargo-release`](https://github.com/sunng87/cargo-release) is capable of bumping these before a release.
> Unify readme between Ash and Ash-window

- Changelog.md
- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash-window/README.md
- ash/Cargo.toml
- changelog: Add all entries for 0.33
- Prepare for ash-0.33 and ash-window-0.7 release
> Update changelog and prepare for ash-0.33 and ash-window-0.7 release

- Changelog.md
- ash/src/util.rs
Fixes https://github.com/MaikKlein/ash/issues/354
`io::Read::read_exact` does not receive `MaybeUninit` memory and a trait implementation can possibly read from our uninitialized vector without `unsafe`, which is UB.  As there is no proper solution to this problem yet (see linked issue), our safest bet is to just take the perf-hit and zero-initialize this vector.
> util: Zero-initialize result to prevent possible uninit memory read

- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/ext/full_screen_exclusive.rs
- ash/src/extensions/ext/tooling_info.rs
- ash/src/extensions/khr/display.rs
- ash/src/extensions/khr/pipeline_executable_properties.rs
- ash/src/extensions/khr/surface.rs
- ash/src/extensions/khr/swapchain.rs
- ash/src/instance.rs
- ash/src/prelude.rs
> ash: Repeatedly call enumeration functions when `VK_INCOMPLETE` is returned

- ash-window/README.md
Just noticed this was out of date on `crates.io` 😄
> Bump `ash-window` version in `README.md`

- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/experimental/amd.rs
- ash/src/extensions/mod.rs
- ash/src/instance.rs
- ash/src/lib.rs
- ash/src/prelude.rs
- ash/src/util.rs
- ash/src/vk/definitions.rs
- ash/src/vk/enums.rs
- ash/src/vk/extensions.rs
- ash/src/vk/features.rs
- ash/src/vk/macros.rs
- generator/src/lib.rs
Saves a bit of unnecessary expansion inside the macro.
> generator: Use `Self` instead of `$name` in macros

- ash/src/vk/extensions.rs
- ash/src/vk/feature_extensions.rs
`syn` has been updated to not remove the `_` again from negative numbers, which previously disappeared in the 1.0 upgrade in 43b5058 ("Upgrade proc_macro2/syn/quote to v1.0 (#351)").
See also https://github.com/dtolnay/syn/releases/tag/1.0.81:
Support arbitrary precision negative literal tokens on rustc 1.56+
> ash: Regenerate negative constants with `syn 1.0.81`

- ash/src/extensions/experimental/amd.rs
- ash/src/vk/bitflags.rs
- ash/src/vk/definitions.rs
- ash/src/vk/macros.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
- generator/src/lib.rs
Fixes #303, fixes #396
The `all()` function only represents bitflags known in the core of Vulkan; it omits all bits added by extensions making this function unrepresentative and has hence been scheduled for removal for quite some time to get rid of the confusion it causes.
Alternatively the generator could be taught to collect bitflags added by extensions, but new extensions get added over time skewing available values in ash versus the current driver/environment.  This makes the value from `all()` unreliable and fragile at best.
---
Keeping this draft so that we can all give a final sign-off on removing `fn all()`. Alternatively we can collect all possible values in the generator, but in that case I prefer to just migrate over to `bitflags!` and provide all extension constants within the …
> vk: Remove misleading `all()`/`-`/`-=` function/ops from bitflags

- ash/src/instance.rs
All Vulkan functions are marked `unsafe` and `enumerate_physical_device_groups` should not be an exception to that.
> instance: Make enumerate_physical_device_groups unsafe

- ash/src/device.rs
- ash/src/extensions/khr/get_memory_requirements2.rs
- ash/src/extensions/khr/get_physical_device_properties2.rs
- ash/src/instance.rs
Point the user in the right direction telling them where to get the length of the mutable slice that has to passed in, and document that these have to be default-initialized (so that `s_type` is set appropriately) and `p_next` can optionally be set too.
> Link _len() functions to their array-getter using intradoc-links

- README.md
Fixes the vulkan-tutorial.com link inside of the readme.
> Fix broken vulkan-tutorial link in README.md

- ash/src/extensions/ext/debug_utils.rs
- ash/src/extensions/khr/pipeline_executable_properties.rs
- ash/src/extensions/khr/timeline_semaphore.rs
Of all the extensions calling get_instance_proc_addr only these two remain that should use the "optimized" device-specific function pointers, since all functions take the device as argument (a child of the device such as a command buffer or queue is also possible, but not applicable here) and may otherwise have to go through a dispatch function [1].
Only VK_EXT_debug_utils remains where all but three of the functions are device (or device-child) specific.  This however requires the autogenerated loader to be separated out into two stages (and debug utils are generally initialized before creating a logical device), making it worth to accept the dispatch function unless this extension struct is split, too.
[1]: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetDevice …
> Use device in pipeline_executable_properties and timeline_semaphore

- ash/src/extensions/khr/maintenance4.rs
This naming was changed at the last resort across the other `_len()` variant calls to be consistent, but the maintenance4 PR didn't have its documentation updated (probably some rust-analyzer "rename symbol" action).
Fixes: 50d58fd ("extensions: Add VK_KHR_maintenance4")
> maintenance4: Fix documented output parameter now named `out`

- ash/src/vk/bitflags.rs
- ash/src/vk/enums.rs
- ash/src/vk/extensions.rs
- generator/src/lib.rs
vk.xml now contains the comment text "Backwards-compatible alias containing a typo" which we can use to detect intentional renames, without needing to specify explicit overrides/exceptions in the generator anymore.
These deprecated constants exist for the sole reason of backwards compatibility which Vulkan cannot permit itself to remove in the C headers, but are unreasonable for crate authors to use anyway due to their `#[deprecated]` annotation whose cargo-check warnings are easy to fix by just using the non-deprecated variant instead.  Furthermore, Ash is still allowing itself to perform breaking changes in its releases making this the perfect time to get rid of all these useless variants and the generator support code that comes with it.  No need to come up with a "more proper" variant …
> generator: Use "Backwards-compatible" comment to detect deprecated alias

- generator/src/lib.rs
The removal of `handle` from `DrawIndirectCount` will slightly interfere with #494, but it remains to be seen which PR lands first.
> Fix new clippy warnings since Rust 1.57

- examples/src/bin/triangle.rs
Use a `PipelineVertexInputStateCreateInfo` builder to pass a slice instead of a pointer and length. Also makes the triangle example a little more consistent with the texture example.
> Simplify triangle example's vertex input state

- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
As per the readme `.build()` should only be called as late as possible, and only if absolutely necessary; such cases include slices that are passed directly to functions.  More precisely, such build calls and the creation of temporary slices should happen inside the same expression as the function call to be sound and completely lifetime-checked.
This pattern of `&[my_builder.build()]` is however not possible when constructing intermediary Vulkan objects that reference the slice.  In the first place this slice goes out of scope after the expression that creates the Vulkan object, which is caught and disallowed by rustc (unless this expression itself ends in `.build()`, which is completely unsound as it makes rustc unable to validate this lifetime dependency).
In the second place - and as …
> examples: Use `slice::from_ref` to not loose lifetime on nested slices

- generator/src/lib.rs
`constants` is iterated twice here: once with a filter, the other time without, and the results are zipped together.  Besides being able to simplify the entire execution to just one `iter()` without intermediary iterators, removing `.zip()` makes it impossible for the results in both iterators to get mismatched when the `filter` inevitably skips elements.  Fortunately no such cases seem to exist, or at least not that effect the resulting generated code.
> generator: Don't zip the same iterator with and without filter

- generator/src/lib.rs
Back when we were still trying to come up with sensible names for "deprecated" aliases (initially introduced as self-supporting constants) that don't adhere to the naming standard but only remain to exist for backwards compatibility, some of these aliases would get the same name as the enum constant they were aliasing, resulting in (compile-time) conflicts.
Now that all those aliases are simply not generated anymore (end-users should just pick the properly named variant) it is not necessary to check for and prevent these conflicts on the generator side anymore.
> generator: Remove now-unnecessary alias-identical check

- ash/src/vk/extensions.rs
- ash/src/vk/feature_extensions.rs
- generator/src/lib.rs
Instead of generating an impl block - together with "Generated from XXX" doc - for every single item that extends an enum type, group all these extensions together in a single `impl` block per extension per type.
This cuts down a couple thousand lines of repeated `impl T` and `#[doc]` annotations, and makes the code more readable at the same time: it is now possible to immediately see exactly all the constants that a certain extension extends a type with.
> extensions: Group enum extension variants together per `impl T` block

- examples/Cargo.toml
- examples/src/lib.rs
Current examples are based on old version of winint that was causing  thread panic on my system, this is well know issue that was already fixed by winint team. I updated examples to use most up to date 0.25.0 version
> examples: Upgrade to winit 0.25

- Changelog.md
- examples/src/lib.rs
On platforms like Android strings use `u8` as character-type instead of `i8` - using the appropriate `c_char` type hides this discrepancy and allows the examples to compile for all platforms.
---
Closes #315 (EDIT: GH can only link and close issues this way, not other PRs)
Opening a separate PR because that one hasn't moved for 1.5 years, even after repeated asking to replace the `s/i8/u8` (which obviously breaks all other platforms) with `c_char`.
> examples: Use c_char for pointer to raw string

- Changelog.md
- ash/src/vk/extensions.rs
- generator/src/lib.rs
This name is emitted by the generator and already known to not contain any null-characters: replace the runtime iteration+comparison (hidden behind `from_bytes_with_nul`) and `.expect()` panic with an `unsafe` "cast" through `from_bytes_with_nul_unchecked`, just like the function-pointer loaders.
> extensions: Don't check extension names for interior nuls at runtime

- Changelog.md
- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash/Cargo.toml
> Prepare release notes for 0.34 (and ash-window 0.8) with Vulkan 1.2.203

- .github/workflows/ci.yml
With more and more features being added to `ash`, now seems to be the right time to make sure the crate is clean of clippy warnings when building without any features in addition to building with the deafult set of features.
> ci: Run clippy once more without default features

- Changelog.md
- ash-window/Cargo.toml
- ash-window/examples/winit.rs
- ash/Cargo.toml
- ash/src/entry.rs
- ash/src/lib.rs
- examples/Cargo.toml
- examples/src/lib.rs
This was found to be unreasonably disruptive to downstream CI configurations. Fixes #525.
I opted to additionally enable `loaded` by default, and reposition `Entry::load` above `Entry::linked`, so that a working configuration is available and easily found out of the box.
> Don't link Vulkan by default

- ash/src/extensions/experimental/amd.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
Following the changes in a053c6a ("Remove unnecessary CString allocation when loading functions (#379)") this addresses the remainder of string allocations in manual extension loading code.
> extensions/amd: Remove unnecessary CString allocations in `fn load`

- ash/src/vk/prelude.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
Fixes #536
When the misleading `all()` function was removed in #478 it also made all color components for `ColorComponentFlags` significantly more verbose to write, see #536.
> Generate `RGBA=R|G|B|A` helper constant for `ColorComponentFlags`

- examples/src/lib.rs
Fixes hangs in case of non-mailbox present modes. I assume acquiring an image from the swapchain hangs when redrawing unconditionally on each incoming event. See https://github.com/rust-windowing/winit/issues/2127 and https://github.com/MaikKlein/ash/issues/541
Tested on Windows with Nvidia gpu
> example: Refactor event loop handling for continuous redraw

- ash/src/device.rs
- ash/src/extensions/khr/get_memory_requirements2.rs
- ash/src/extensions/khr/get_physical_device_properties2.rs
- ash/src/extensions/khr/get_surface_capabilities2.rs
- ash/src/extensions/khr/maintenance4.rs
- ash/src/instance.rs
Originally introduced in [#489] this inserts the array-length equality check everywhere else: in the supposedly invalid and inexistant event where Vulkan suddenly returns less items (`count` has been modified) than were originally queried through respective `_len()` functions (or more likely: a slice of invalid length passed by the user) and some elements at the end of the slice are left uninitialized, panic.
Wherever there is valid concern or possibility for this to happen - or to circumvent assertions and panics altogether - mutable references to mutable slices should be passed allowing the length to be promptly updated.
[#489]: https://github.com/MaikKlein/ash/pull/489#discussion_r753020089
> Assert that Vulkan array-getters return the same length

- ash-window/Cargo.toml
`raw-window-handle 0.3.4` was pushed as a "semver-trick-like" patch release, implementing the `0.3` trait for the `0.4` crate release [74].  This allows `ash-window` as a window-handle "consumer" crate to accept both `0.3` and i`0.4` handles from consumer crates simultaneously.  To ensure this patch release is available even when users omit regular `cargo update` or build with `-Z minimal-versions`, set the minimal patch version in `Cargo.toml` to it.
[74]: https://github.com/rust-windowing/raw-window-handle/pull/74
CC @dvc94ch, https://github.com/MaikKlein/ash/pull/505#issuecomment-1009181013
> ash-window: Require at least `raw-window-handle 0.3.4` for 0.4 interop

- examples/Cargo.toml
- examples/src/bin/texture.rs
Examples-only excerpt of #547, as the generator and ash-window example changes need more work.  Fixes #550.
> examples: Update winit to 0.26 and image to 0.23

- ash/src/vk/macros.rs
Closes #546
So that vk_bitflags may be used directly in const contexts more ergonomically, similar to bitflags: https://docs.rs/bitflags/1.3.2/bitflags/example_generated/struct.Flags.html
> Convert `vk_bitflags_wrapped!` methods to `const fn`

- Changelog.md
- README.md
- ash-window/README.md
And drop the deprecated =/- markdown syntax from our readme: this is analogous to #/## for a h1/h2 header, instead of defining a title and (usually smaller font) subtitle or description.
> changelog: Add entries for recent PRs #545, #534, #553, #551, #549

- Changelog.md
- ash/src/vk/prelude.rs
- examples/src/bin/texture.rs
- examples/src/bin/triangle.rs
- examples/src/lib.rs
When using `ash`, I frequently find myself wishing that converting between 2D/3D extents was less verbose, since it's so common. Likewise, you need to convert from an `Extent2D` to a `Rect2D` any time you want to start a render pass that affects an entire framebuffer.
> Add conversions between Extent2D, Extent3D and Rect2D

- .github/workflows/ci.yml
- Changelog.md
- ash/src/extensions/khr/get_surface_capabilities2.rs
- ash/src/vk/prelude.rs
I was pretty certain our documentation was at least build-tested since that's generally one of the first things I check/PR on the crates I touch... Supposedly not here. It allowed some broken links to slip in, most recently in #530 and #537 where I _wrongly assumed_ the CI was having my back. ~Let's make sure it fails now before pushing the necessary fixes.~ CI is properly working and finding+disallowing issues: https://github.com/MaikKlein/ash/runs/4865846622?check_suite_focus=true
> ci: Build-test documentation with warnings disallowed, and fix broken links

- ash/src/device.rs
- ash/src/entry.rs
- ash/src/extensions/khr/get_memory_requirements2.rs
- ash/src/extensions/khr/get_physical_device_properties2.rs
- ash/src/extensions/khr/get_surface_capabilities2.rs
- ash/src/extensions/khr/maintenance4.rs
- ash/src/instance.rs
- ash/src/vk/prelude.rs
Suggestion from [#559].
[#559]: https://github.com/MaikKlein/ash/pull/559#discussion_r790178735
~Note that `Self::` in `_len()` function docs hasn't been replaced (yet?) as the longer function names make this format rather verbose.  However, we should probably prefer docs readability over code readability?~
> Use link text in docs to omit `Self::` prefix in rendered docs

- Changelog.md
- ash/Cargo.toml
- ash/src/vk/aliases.rs
- ash/src/vk/bitflags.rs
- ash/src/vk/const_debugs.rs
- ash/src/vk/constants.rs
- ash/src/vk/definitions.rs
- ash/src/vk/enums.rs
- ash/src/vk/extensions.rs
- ash/src/vk/feature_extensions.rs
- ash/src/vk/features.rs
- ash/src/vk/native.rs
Vulkan 1.3 is out, with many extensions stabilized.  This'll have to remain draft until the next spec version (hopefully next week) where (again, hopefully) https://github.com/KhronosGroup/Vulkan-Docs/pull/1746 is incorporated - otherwise we'll have to work around in our generator :(
> Update Vulkan-Headers to 1.3.206

- Changelog.md
- ash/src/device.rs
- ash/src/entry.rs
- ash/src/instance.rs
Depends on #563
Now the loaders are called so that `fp_1_3()` is available for `Entry` (not relevant because it's empty), `Instance` and `Device`.  Also implement Rust'y wrapper functions for all new commands that are added in Vulkan 1.3.
> Add helper wrappers for Vulkan core 1.3 `Instance` and `Device` functions

- ash/src/entry.rs
```
warning: unnecessary `unsafe` block
--> ash\src\entry.rs:146:47
|
145 |     pub unsafe fn from_static_fn(static_fn: vk::StaticFn) -> Self {
|     ------------------------------------------------------------- because it's nested under this `unsafe` fn
146 |         let load_fn = |name: &std::ffi::CStr| unsafe {
|                                               ^^^^^^ unnecessary `unsafe` block
|
= note: `#[warn(unused_unsafe)]` on by default
```
> Fix Rust 1.61 unsafe in unsafe warning in Entry::from_static_fn

- Changelog.md
- ash/src/extensions/nv/device_diagnostic_checkpoints.rs
To match all other functions which accept an array of to-be-initialized structs with a `pNext` pointer that is possibly initialized by the caller.
> `VK_NV_device_diagnostic_checkpoints`: Enable passing `pNext`-initialized structs to `get_queue_checkpoint_data`

- .github/workflows/ci.yml
- ash-window/Cargo.toml
- ash/Cargo.toml
[#590] introduced an unsuspecting MSRV bump.  While we're pro-ba-bly fine having these at the benefit of better code (in this case more appropriate `const` annotations), they should at least be clear to us when merging through a CI failure (or up-front bump of this version in the CI script).  At the same time setting [`rust-version` in `Cargo.toml`] provides a more helpful "requires newer rustc" error message (since Rust 1.56.0) instead of showing potentially tons of irrelevant compile errors in this crate to the user.
[#590]: https://github.com/MaikKlein/ash/pull/590
[`rust-version` in `Cargo.toml`]: https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=pack#the-rust-version-field
> Set MSRV through `rust-version` in `Cargo.toml` and validate in CI

- ash/src/device.rs
- ash/src/instance.rs
- ash/src/prelude.rs
- ash/src/vk/definitions.rs
- generator/src/lib.rs
I did not inline `load`, any of the wrappers that invoke `read_into_*_vector` helpers, or (for now) extensions methods. In theory this should be a nice clean overhead reduction at runtime. Data on buildtime impact would be great!
> Inline Default impls and trivial instance/device wrapper methods

- Changelog.md
- ash/Cargo.toml
- ash/src/vk/bitflags.rs
- ash/src/vk/const_debugs.rs
- ash/src/vk/definitions.rs
- ash/src/vk/extensions.rs
Note that `video.xml` is now added to `Vulkan-Headers`, which we can start using in the future when bitfield support lands in our XML parser and the generator - or bitfields are replaced with proper flags.
> Update Vulkan-Headers to 1.3.211

- README.md
Tested with version 1.3.204.1.
The following displays the triangle example on my Mac:
```
VULKAN_SDK=$HOME/VulkanSDK/1.3.204.1/macOS \
DYLD_FALLBACK_LIBRARY_PATH=$VULKAN_SDK/lib \
VK_LAYER_PATH=$VULKAN_SDK/share/vulkan/explicit_layer.d \
VK_ICD_FILENAMES=$VULKAN_SDK/share/vulkan/icd.d/MoltenVK_icd.json \
cargo run --bin triangle
```
> Fix instructions for running the examples on a Mac.

- ash/src/entry.rs
On certain platforms including Android and `aarch64` `c_char` is unsigned, resulting in the same `u8` type as the byte-string here making the cast redundant.
Just like any other code calling `get_instance_proc_addr`, use `CStr::from_bytes_with_nul_unchecked` which abstracts away any pointer-cast.
> ash/entry: Fix `trivial_casts` lint warning on Android/aarch64

- Changelog.md
- ash/src/extensions/ext/mod.rs
- ash/src/extensions/ext/sample_locations.rs
CC @coffeenotfound
Note that this is again a "device" extension that we can't load as such because it needs to load an instance function that operates on a `physical_device`.
> extensions/ext: Add VK_EXT_sample_locations

- examples/src/lib.rs
When trying to run the examples on macOS, I was seeing the following validation errors:
<details>
<summary>Error: vkCreateDevice: VK_KHR_portability_subset must be enabled [...]</summary>
ERROR: VALIDATION [VUID-VkDeviceCreateInfo-pProperties-04451 (976972960)] : Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x6000001f8020, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x6000001f8020[] supports it The Vulkan spec states: If the VK_KHR_portability_subset extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensionNames must include "VK_KHR_portability_subset" …
> examples: Fix validation errors on macOS and iOS

- ash/Cargo.toml
- ash/src/lib.rs
Closes #583
Just copied and pasted the Cargo.toml feature comments into lib.rs based on the first recommendation on the [cargo feature docs](https://doc.rust-lang.org/cargo/reference/features.html#feature-documentation-and-discovery) (which links [regex](https://github.com/rust-lang/regex/blob/1.4.2/src/lib.rs#L488-L583) as reference). Also added a note in Cargo.toml so that anyone who updates features in the future knows to also update the docs.
**Reasoning:**
Makes feature descriptions more accessible (see discussion on issue #583). Currently you can see the list of ash features on [docs.rs](https://docs.rs/crate/ash/latest/features) but need to get Cargo.toml to see what they do. All three features seem to have potential utility for users imo.
> Document crate `feature`s in library docs

- Changelog.md
- ash/src/entry.rs
Looks like these went missing from #606.
@Ralith where do you generally put the cutoff point?  That is, this file has some `Display`/`Error`/`From` `impl`s which could get the same treatment? How about `load_checked()`/`linked()`/`load()`? Anything else in `utils.rs` that we want to cover?
> Inline trivial `Entry` wrapper methods and `impl` functions

- ash/src/version.rs
This seems to have been forgotten in #412.
> Remove unused `version.rs` module file from git

- Changelog.md
- ash/src/extensions/khr/swapchain.rs
These are also made available by `VK_KHR_device_group` when `VK_KHR_swapchain` (and for certain functions only the underlying `VK_KHR_surface` extension) is enabled.
> extensions/khr: Implement additional `Swapchain` functions since Vulkan 1.1

- ash/src/device.rs
Supersedes #640
A slice is designed to be a cheap view into a continuous segment of memory and easily recreated with a different offset and size.  This can be used to our advantage to let the user set exactly how many items they want to request, while ensuring all returned slots are filled on success or otherwise return `NOT_READY` if not enough query results could be copied to user memory (or block if the `WAIT` flag is set).
This also opens the door to accepting `MaybeUninit` in the future and returning the initialized slice in the `VkResult::Ok(here)` case.
> device: Replace `query_count` parameter in `get_query_pool_results` with `data.len()`

- ash-window/Cargo.toml
- ash-window/examples/winit.rs
We'll bump to 0.26 now so that we can land #505 with `raw-window-handle 0.4`, and shortly after bump to `raw-window-handle 0.5` + `winit 0.27` which have to be updated in unison. I'll perhaps make an intermediary release for `ash-window` to give users the opportunity to use `raw-window-handle 0.4`, which isn't (as a _consumer_) backwards nor forwards compatible with neither `0.3` nor `0.5`.
> ash-window: Upgrade `winit` example to `0.26`

- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash-window/src/lib.rs
Note that this depends on one of the many winit 0.25 example upgrades (though we'll require 0.26 to make `raw-window-handle` 0.4 work) in order to succeed compilation on the examples.
---
Not sure about the timing on this one: raw-window-handle just came out, and winit 0.26 too.  There's a compatibility in 0.3.4 that allows consumers like this ash-window crate to consume the 0.4 handle (because the trait is implemented for it) produced by ie. winit, so there's a good reason to stay on 0.3.4 for longer to have wider adoption before migrating the ash-window crate - which is unfortunately tied in to the ash version!  This just provides a git branch/rev for crate authors to use if they desire to deduplicate their raw-window-handle dependency in the crate graph.
I wonder if we can use a lower …
> ash-window: Upgrade to raw-window-handle 0.4.2

- ash/src/vk/prelude.rs
The report at https://github.com/rust-lang/rust/issues/93205 was closed as it has presumably been fixed in https://github.com/rust-lang/rust/pull/93805 which has long trickled down into stable releases, and I cannot reproduce the issue on `1.62.1` anymore (latest stable as of writing) 🎉
This workaround was originally added in #559.
> vk/prelude: Drop upstream-fixed `Self::` doc workaround

- Changelog.md
- ash/src/lib.rs
- ash/src/vk/definitions.rs
- ash/src/vk/prelude.rs
- generator/src/lib.rs
Depends on #613
In Vulkan layers extracing a structure based on its `s_type` is a common operation, but comparing against an enum value and subsequently casting to the right type is verbose and error-prone.
By generating a `const STRUCTURE_TYPE` with the given value for every Vulkan structure it becomes possible to implement a macro that abstracts this logic away in a safer way.
> ash: Add `const STRUCTURE_TYPE` to all Vulkan structures for matching with `match_struct!` macro

- Changelog.md
- ash/src/extensions/khr/ray_tracing_pipeline.rs
Because the capacity is allocated but the length of the vector is not set, the vec returned from `get_ray_tracing_capture_replay_shader_group_handles` will always appear to be empty. I checked for other mistakes of this nature and did not locate any.
> extensions/khr/ray_tracing_pipeline: Set length of capture-replay shader handle buffer after filling

- ash-window/README.md
It seems there's no gitter channel for `ash-window` (404), and since everyone is in the `ash` channel already, just use the same one.
> ash-window: Link to the `ash` gitter instead of nonexistent `ash-window`

- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash-window/README.md
- ash-window/examples/winit.rs
- ash-window/src/lib.rs
- examples/Cargo.toml
- examples/src/lib.rs
Depends on #505, #643, https://github.com/norse-rs/raw-window-metal/pull/5
> ash-window: Upgrade to raw-window-handle 0.5.0

- ash/src/vk/definitions.rs
- generator/src/lib.rs
Prepare the generator for more struct fields that have nested "dynamic arrays" with a hardcoded size of `1` (effectively arrays with pointers to single objects) in `vk.xml`s `len` attribute.  These structs are introduced by `VK_EXT_opacity_micromap` in 1.3.230.
---
The implementation itself is a bit nasty but not something I feel like making a fuss about right now in light of a generator rewrite - just something we should be generating so that we can compare it to the output of the new generator and make sure this remains supported going forward.  At the same time this allows us to upgrade to and beyond 1.3.230, and un-breaks the Vulkan headers CI where Ash is currently generated and build-tested.
> generator: Support nested arrays in builders without hardcoding

- Changelog.md
- ash/src/extensions/ext/acquire_drm_display.rs
- ash/src/extensions/ext/mod.rs
Note that https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4136 prevents the use of `vkGetDrmDisplayEXT` while using  `VK_LAYER_KHRONOS_validation`.
> extensions/ext: Add VK_EXT_acquire_drm_display

- ash/src/extensions/ext/acquire_drm_display.rs
- ash/src/extensions/khr/display.rs
- ash/src/prelude.rs
It is undefined behaviour to construct a safe object by calling `MaybeUninit::assume_init()` when the object in question hasn't been initialized by anything (in this case the underlying Vulkan call) at all, even if the object is never "used".  Postpone the `assume_init()` call until after checking if `vk::Result::SUCCESS` has been returned by the native implementation, by introducing a new `assume_init_on_success()` helper that takes a `MaybeUninit<T>`.
> extensions: Only call `assume_init()` when Vulkan returns `SUCCESS`

- .github/workflows/ci.yml
`bytemuck` recently bumped its MSRV to 1.60 which is incompatible with what we're currently advertising.  Fortunately this doesn't affect MSRV of the publicly published crates, but only `dev-dependencies` inside `ash-window` via `winit`: make sure the CI doesn't reject this.
```console
$ cargo tree -i bytemuck
bytemuck v1.12.3
├── image v0.24.4
│   └── examples v0.1.0 (ash/examples)
├── safe_arch v0.5.2
│   └── tiny-skia v0.7.0
│       └── sctk-adwaita v0.4.3
│           └── winit v0.27.5
│               └── examples v0.1.0 (ash/examples)
│               [dev-dependencies]
│               └── ash-window v0.11.0 (ash/ash-window)
│                   └── examples v0.1.0 (ash/examples)
├── tiny-skia v0.7.0 (*)
└── tiny-skia-path v0.7.0
└── tiny-skia v0.7.0 (*)
```
> CI: Only MSRV-test published `ash` and `ash-window` crates

- ash-window/src/lib.rs
- ash/src/device.rs
- ash/src/extensions/khr/acceleration_structure.rs
- ash/src/extensions/nv/ray_tracing.rs
- ash/src/util.rs
- ash/src/vk/definitions.rs
- examples/src/lib.rs
- generator/src/lib.rs
`.cast()` allows changing the pointer type without hiding (accidental) mutability changes (noting that `*mut` still coerces to `*.const`).
For mutability changes Rust 1.65 included `cast_mut()` and `cast_const()`, but those would bump our MSRV too eagerly for now.
> Replace `as *...` raw pointer-type changes with more explicit `.cast()`

- ash/src/device.rs
- ash/src/extensions/khr/display_swapchain.rs
- ash/src/extensions/khr/ray_tracing_pipeline.rs
- ash/src/prelude.rs
The entire reason for calling `unsafe` `set_len()` after the Vulkan driver function call is to ensure the `Vec` never gives safe access to uninitialized values (as allocted via `Vec::with_capacity()`).  This contract is broken within the implementation of these functions by temporarily setting a nonzero length when the Vulkan driver may not have initialized the underlying data at all, and communicated this by returning an error code.
Simply check the error code first, before jumping to a now-infallible codepath that calls `.set_len()` and always returns `Ok()`.
We have to see what should happen in `create_graphics_pipelines()` and `create_compute_pipelines()` which _always_ return the underlying `Vec` even on errors... 😰. Only do this [if `VK_PIPELINE_COMPILE_REQUIRED_EXT` is …
> Call `Vec::set_len()` after checking for Vulkan errors

- Changelog.md
- ash/src/extensions/ext/descriptor_buffer.rs
- ash/src/extensions/ext/mod.rs
> extensions/ext: Add VK_EXT_descriptor_buffer

- Changelog.md
- ash/Cargo.toml
Since we don't seem to be gaining much traction on the `vk.xml` fixes (the ball is with Khronos to come up with a better way to represent these types) I'd like to get a patch release out now with new features and extensions requested by the community.  We can always release more patch versions, there's no harm in that.
I'd like to get #629 / #630 / #631 in for this release too, and perhaps #614 if we can.  As soon as those are merged to `main` I'll backport them to the `0.37-stable` branch and update the changelog accordingly.
After the release I'll update the version and changelog on `main` to reflect what has landed in `0.37.1`, and what has yet to come in a future release.
> Release `ash 0.37.1`

- ash/src/vk/const_debugs.rs
- ash/src/vk/extensions.rs
- generator/src/lib.rs
It is unlikely that disabled, reserved extensions (without naming whatsoever) are used through Ash bindings generated from Vulkan-Headers releases, and are best ignored to reduce diff noise and spurious issues [1] with unfinished extension definitions.
This approach matches what is defined in the registry spec for `supported="disabled"` [2]:
use `supported="disabled"` to indicate this extension should never be processed.
[1]: KhronosGroup/Vulkan-Docs#1549
[2]: https://github.com/KhronosGroup/Vulkan-Docs/blob/b4e8cd820b2487bc892b391fb26b49501473a6a6/registry.txt#L1302-L1306
---
Let me know if someone is using our bindings to access in-development extensions through these means though! (But in that case I expect a local substitution in `vk.xml` + regeneration...)
> generator: Do not generate code for "disabled" extensions

- Changelog.md
Looks like [my edit for delaying the merge of #448](https://github.com/ash-rs/ash/pull/448#issuecomment-1345634661) came in just too late, as I was unable to edit this in on the phone at 1:30am :)
> changelog: Document removal of `"disabled"` extension code

- ash/src/vk/enums.rs
- generator/src/lib.rs
Rustdoc since 1.66 points out that `<<ref>>` is malformed HTML, and the resulting `<<devsandqueues-lost-device>>` isn't very helpful to users.  Convert it to the relevant link in both documentation and `Result` `Display` to solve both issues at once.
This may be a bit overzealous since there's only one documentation string containing these (aside from `#define`s around `VK_MAKE_VERSION`) but it's almost easier to fix generically than to make a workaround for this specific string.
> Replace `<<ref>>` in documentation with link to `ref`

- examples/src/lib.rs
Strangely some no-op cast remained in the codebase, and are only now caught since Rust 1.66.  In both cases the input value is already of the correct type (independent of the platform).
> examples: Remove unneeded casts as pointed out by Rust 1.66

- examples/src/bin/texture.rs
Minor fix for wrong error description
> examples: Fix error description in texture example

- ash-window/Cargo.toml
- ash-window/examples/winit.rs
- ash/Cargo.toml
- ash/build.rs
- ash/src/prelude.rs
- ash/src/util.rs
- examples/Cargo.toml
- examples/src/lib.rs
- generator/Cargo.toml
- generator/src/lib.rs
Closes #704
Note that there is an unrelated `clippy::seek_to_start_instead_of_rewind` fix.
~And one instance of `clippy::uninlined_format_args` in generator.rs cannot be fixed and must be allowed.~
> fix `clippy::uninlined_format_args`

- generator/src/lib.rs
An upcoming extension will ship with an untyped `pCode` member (`void *`) including a valid `len` field pointing to a `codeSize` field rather than obscure Latex math and a `/4` expression in `altlen`.  Limit the scope of our workaround for that SPIR-V-specific `pCode` field to `VkShaderModuleCreateInfo`.
> generator: Limit `pCode` member workaround to `VkShaderModuleCreateInfo`

- .github/workflows/ci.yml
- Changelog.md
- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash/Cargo.toml
CC #703
These dependencies fail to resolve on older Rust/cargo versions before even complaining about them being a too-high MSRV.
> Bump MSRV to 1.60 to accomodate for `winit 0.28`/`objc` requirement

- Changelog.md
Commit c66db26 ("device: Replace `query_count` parameter in `get_query_pool_results` with `data.len()` (#644)") removed this parameter in favour of using `data.len()` to make it more obvious to use an appropriate element type that matches the kind of request (see also #639) so that the stride is filled in correctly, but it was not mentioned in the changelog yet.
> changelog: Document removal of `query_count` parameter from `get_query_pool_results()`

- .github/workflows/ci.yml
- README.md
- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash-window/README.md
`raw-window-handle 0.5.1` bumped from 1.60 to 1.64 in a semver-compatible release, failing our CI infrastructure overnight.
~Keep the `ash` version at `1.60` for now.~ Lower `ash` to 1.59 because the original bump in #709 was only to match `winit 0.28`/`objc`, both of which are not used by the `ash` crate.
> ash-window: Bump MSRV to 1.64 to match `raw-window-handle 0.5.1`

- ash/src/device.rs
- ash/src/extensions/khr/external_memory_fd.rs
- ash/src/extensions/khr/maintenance4.rs
Found it annoying that some functions have arguments called `create_info` when the struct type isn't actually a `create_info` e.g.
```rust
pub unsafe fn cmd_begin_render_pass(
&self,
command_buffer: vk::CommandBuffer,
create_info: &vk::RenderPassBeginInfo,
contents: vk::SubpassContents,
)
```
So I looked through all the `create_info` function arguments and renamed the ones which didn't make sense to match whatever the vulkan spec calls them e.g. `memory_reqirements`
> Rename some function arguments to match the vulkan spec

- ash/src/vk/extensions.rs
- ash/src/vk/features.rs
- generator/Cargo.toml
- generator/src/lib.rs
For the upcoming `api` attribute in `vk.xml` commands also need to be processed through `vk-parse` which has support for all the new attributes, while `vkxml` is deprecated and completely untouched for years.  This conversion unfortunately requires whipping up yet another quick-and-dirty `nom` parser of a specific subset of C used in `vk.xml` to describe parameter signatures.  This PR shows that conversion is complete and provides no accidental semantic differences.
Also update `vk-parse` to `0.9` which contains a new `code` field on `CommandParam` (`<param>` element) to be able to inspect the code signature of individual parameters rather than parsing them out of (and matching them back to `vk-parse`'s `params` array!) the `<command>` / `CommandDefinition` as a whole: …
> generator: Handle `<command>` via `vk-parse` types and `nom`

- Changelog.md
- ash/src/extensions/ext/mod.rs
- ash/src/extensions/ext/shader_object.rs
Depends on #723
Lots of function copy-paste because this extension enables a bunch of functions also provided by `extended_dynamic_state*`, which is something I hope we can streamline with the new generator through "some kind of" this-or-that-or-that extension machinery.
> extensions/ext: Add VK_EXT_shader_object device extension

- generator/src/lib.rs
Turns out we were doing the wrong thing for the right reason: the `aliases` here aren't `vk.xml` aliases: they are renames.  When generating function pointers for extensions, a list of command _definitions_ is collected, which can only ever be "root" `command`s.  Extensions typically reference stabilized `command`s under an alias with the vendor tag suffixed, which the `Fn` struct field name is renamed to using this `aliases` - now replaced with `rename_commands` - list, while generating the rest of the "function pointer" command bits using the "root" `command` (as this mostly pertains the parameters and return type).  With that explanation it becomes clear why `generate_extension_commands()` was creating an "alias" mapping from stabilized name to vendor-suffixed extension name, and calls …
> generator: Borrow all `command` names and disentangle "aliases"

- .github/workflows/ci.yml
There's no reason to use these steps anymore: besides being old, unmaintained, and spitting out NodeJS deprecation warnings, GitHub's `runner-images` come preloaded with all Rust tools and components we need, and the syntax to run commands is more efficient, much shorter and more apprehensible by simply matching what we'd use on our own command-line, too.
> CI: Replace deprecated `actions-rs` with simple `run: cargo ...`

- .github/workflows/ci.yml
- generator/src/lib.rs
Fixes #653
Some users are confused by seeing wildly different output after running the generator, which is simply solved by running `rustfmt`.  As this is both confusing and "somewhat" slow, invoke `rustfmt` directly within the generator by piping string contents through it before redirecting to disk.  This not only makes the output consistent, it is the fastest way to reformat generator changes by omitting the round-trip to disk entirely, nor having `rustfmt` recursively go through the workspace and all files (including those that are not generated).
On a many-core machine these times are a bit skewed, but I want to include them to prove the "speed" point nevertheless, even if simplicity and consistency is the main reason to make this change:
Before:
time ./target/debug/generator && time …
> generator: Run `rustfmt` over generated output before writing to disk

- README.md
- ash-window/README.md
Fixes #742
#602 introduced builder functions directly on the raw Vulkan struct types by using lifetime borrows which are FFI compatible (ABI is identical) wuth raw pointers, simplifying the whole system and protecting the user against losing lifetimes upon calling `.build()`.  However, this change wasn't propagated through to the `README` so the code snippets were still showcasing removed `::builder()` and `.build()` functions and documenting "the `.build()` footgun" which doesn't even exist anymore 🎉
> README: Remove deprecated `builder()` snippets and guidelines

- ash/src/vk/definitions.rs
- generator/src/lib.rs
Fixes #450
Don't omit the `attachment_count()` builder method, because it is valid to set the number of attachments without providing attachments in the `IMAGELESS` case.
Also change the generator array lookup to use the name of the count field that is allowed to have a builder method, rather than the name of the field that would use this as `len` field and hence cause it to be skipped.
> Expose `FramebufferCreateInfo::attachment_count` builder for `IMAGELESS`

- Changelog.md
- ash/src/extensions/khr/acceleration_structure.rs
- ash/src/extensions/khr/external_memory_fd.rs
- ash/src/extensions/khr/external_memory_win32.rs
- ash/src/extensions/khr/get_surface_capabilities2.rs
Fixes #740
Version 2 of `get_physical_device_surface_capabilities` and the matching `vk::SurfaceCapabilitiesKHR` struct exist solely to provide an `sType` and `pNext` field to allow extending the original query with additional data via extension structs.  However, this API when introduced in #530 only returns the `default()`-initialized struct making it just as constrained as `get_physical_device_surface_capabilities()`.  Solve this by taking `vk::SurfaceCapabilities2KHR` as `&mut` just like any similar API.
And just like this, do the same for the remaining:
- `AccelerationStructure::get_acceleration_structure_build_sizes()`
- `ExternalMemoryFd::get_memory_fd_properties()`
- `ExternalMemoryWin32::get_memory_win32_handle_properties()`
In case these structs get extended somewhere down the …
> extensions/khr: Take the remaining `p_next`-containing structs as `&mut`

- Changelog.md
- ash/src/extensions/khr/device_group_creation.rs
Looks like #630 typo'd the argument for `DeviceGroupCreation::new()` by unnecessarily requiring a move (`Clone`) of `Entry` just to call `get_instance_proc_addr()` on it.  Replace this with a borrow to match all other extensions.
> extensions/khr/device_group_creation: Take borrow of `Entry` in `new()`

- Changelog.md
- ash/src/extensions/khr/xlib_surface.rs
- ash/src/vk/platform_types.rs
Fixes #749
Xlib defines `Display` as follows:
typedef struct _XDisplay Display;
And then always references this type as a pointer to it, e.g. `Display *`.  The same happens in `ash`, where `Display` is only ever referenced as a raw pointer via `*mut Display`, so making `Display` itself a type alias to `*mut c_void` is wrong and confusing.  Switch it back to a `c_void` to match the forward-declared (but otherwise undefined) `struct _XDisplay`.
> Define `Display` as `c_void` instead of `*mut c_void` to match Xlib

- Changelog.md
- ash/src/device.rs
- ash/src/entry.rs
- ash/src/instance.rs
- ash/src/vk/extensions.rs
- ash/src/vk/features.rs
- generator/src/lib.rs
Fixes #442, cc @Rua
These functions don't contribute anything and should be removed to clean up the `features` and `extensions` files, while now also not showing in the documentation anymore.  The structs remain in place for associated constants but are replaced with true unit-like structs (no curly brackets anymore), and unneeded `unsafe impl Send/Sync` are removed as well.
As these `load()` functions have been removed from the empty feature-levels on `Entry` and `Device` as well, rather than instantiating the unit structs and returning those the fields and `fp_vX_X()` getters have been removed entirely.
> Drop `load()` functions from empty `Fn` `struct`s

- Changelog.md
- ash/src/vk/definitions.rs
- generator/src/lib.rs
We already do this for hand-written extension functions but can now also implement it for setters since `vk_parse` fields are available within the builder generator code: when a field refers to another field for setting its `objecttype`, that `VkObjectType` field setter is omitted and instead assigned when the object is set, based on a type generic that implements the `Handle` trait instead of an untyped `u64`.
---
Note that most of this diff is merely code motion: some necessary cleanups such as replacing tuples with infinitely-more-self-descriptive structs.
> Generate generic builder setters for fields taking an `objecttype`

- Changelog.md
- ash/src/extensions/ext/full_screen_exclusive.rs
- ash/src/extensions/khr/device_group.rs
- ash/src/extensions/khr/device_group_creation.rs
- ash/src/extensions/khr/swapchain.rs
This is a minimal, semver-compatible backport of #734 to the `0.37-stable` branch, warning Ash users of the problem outlined below while the issue is properly being solved in the next breaking Ash release (by separating `Instance` and `Device` functions in the generator to avert this problem entirely while also always providing optimal `Device`-specific functions for extension wrappers that are currently already loading _everything_ via `Instance` to forgo the problem).
As discovered and detailed in #727 a few extension wrappers were loading and calling `Instance` functions via `Device` and `get_device_proc_addr()` which is [defined] to only return non-`NULL` function pointers for `Device` functions.  Those wrapper functions will always call into Ash's panicking NULL-stub functions as the …
> [0.37-stable] extensions: Provide `new_from_instance()` fallback for `Instance` functions

- Changelog.md
- ash/src/extensions/ext/calibrated_timestamps.rs
Per spec `max_deviation` is a single value, and not a vector.
Closes https://github.com/ash-rs/ash/issues/737
> extensions/ext: Make `get_calibrated_timestamps()` return single value for `max_deviation`

- Changelog.md
- ash/src/device.rs
- ash/src/entry.rs
- ash/src/instance.rs
Adds a constructor to build a device from a handle + functions. 
Helps with interoperability with other vulkan wrappers where the user might have loaded the functions already.
> Allow building `Entry`/`Instance`/`Device` from handle+fns

- Changelog.md
- ash/src/entry.rs
We don't mark any of the extern calls to Vulkan function-pointers safe except for a few `Entry` functions.  Their safety contract was easy to validate, but now that we exposed a constructor function to let the user provide function pointers in the form of `Entry::from_parts_1_1()` it is no longer safe to assume that we are calling the function that adheres to the contract specified in the Vulkan reference.
Because we don't rigorously do this validation and safe-marking anywhere else either, mark these function calls as `unsafe`.
Related discussion chain: https://github.com/ash-rs/ash/pull/748#discussion_r1186794284
> entry: Mark `Entry::from_parts_1_1()` as `unsafe`

- Changelog.md
- ash/Cargo.toml
It is high time to release the latest incremental non-breaking changes as `0.37.3` and pave the way for a breaking `0.38` release with many helper-API improvements.
I might delay this until merging and backporting #625.
> Release `ash 0.37.3`

- Changelog.md
- ash/src/extensions/khr/device_group_creation.rs
I ended up fixing this via deprecation on the `0.37-stable` branch, but forgot to fix it on `master` (and it doesn't seem to have slipped into any other (open) PR).
> Rename `vk::Instance`-returning function from `device()` to `instance()`

- Changelog.md
- ash/src/extensions/nv/memory_decompression.rs
- ash/src/extensions/nv/mod.rs
Add support for `VK_NV_memory_decompression`
> extensions/nv: Add VK_NV_memory_decompression

- generator/src/lib.rs
Otherwise enums with the MSFT suffix fail to parse.
> Add MSFT vendor tag for enum variants

- Changelog.md
- ash/src/extensions/amd/mod.rs
- ash/src/extensions/amd/shader_info.rs
Fixes #771, depends on #772, CC @kvark
> extensions/amd: Add VK_AMD_shader_info

- ash/src/extensions/nv/ray_tracing.rs
Old and probably unused/deprecated extension now that `VK_KHR_ray_tracing` exists and is stabilized for quite some time, but it's still wrong to zero-initialize `sType`.
Additionally checking all other `mem::zeroed()` calls made me stumble across another PR where `mem::MaybeUninit::zeroed()` was used and `assume_init()` after a function returned successfully.  Perhaps we should switch to that on all occasions (and possibly replace `zeroed()` with `uninit()`)?
> nv/ray_tracing: Initialize tagged struct with `default()`

- .github/workflows/ci.yml
- generator/src/lib.rs
We have some conditional code specific to Mac and iOS which is currently untested in the CI, allowing non-compiling code in PRs like https://github.com/ash-rs/ash/pull/795 to go unnoticed.
Additionally, fix the clippy lints pointed out by new Rust versions.
> CI: Cross-lint for Mac, iOS and Windows

- Changelog.md
- ash-window/src/lib.rs
- ash/src/extensions/khr/external_fence_win32.rs
- ash/src/extensions/khr/external_memory_win32.rs
- ash/src/extensions/khr/external_semaphore_win32.rs
- ash/src/vk/platform_types.rs
The `windows` crate treats these as `isize` rather than raw void pointers:
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HWND.html
And `raw-window-handle 0.6` recently started to do the same:
https://github.com/rust-windowing/raw-window-handle/pull/136
However, the win32 documentation still states that these should be `PVOID`:
https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types
Hence I'm not super confident what the right step forward is: `isize` is a breaking change (we'll do a breaking release soon™™™ anyway) but plays more nicely with interop with other crates. @madsmtm was your motivation for `raw-window-handle` also the type representation in windows-rs?
> platform_types: Convert Windows `HANDLE` types to `isize`

- Changelog.md
- ash/src/device.rs
- ash/src/extensions/nv/cuda_kernel_launch.rs
- ash/src/extensions/nv/mod.rs
> extensions/nv: Add VK_NV_cuda_kernel_launch extension

- .github/workflows/ci.yml
- .gitmodules
When using a `git` reference on this repo, `cargo` will unnecessarily clone the `Vulkan-Headers` submodule (which is only needed by maintainers together with the `generator`).  By setting the update mode to `none` (https://git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-submoduleltnamegtupdate) this is disabled, and `git submodule update` will now also no longer fetch/clone/update the repository unless `--checkout` is used (https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-checkout).
I.e. running `cargo update` on a repo with a `git` dependency on `ash`:
Updating git repository `https://github.com/ash-rs/ash`
Skipping git submodule `https://github.com/KhronosGroup/Vulkan-Headers` due to update strategy in .gitmodules
> gitmodules: Disable `update` to prevent cloning on cargo checkout

- Changelog.md
- ash/src/vk/definitions.rs
- generator/src/lib.rs
Fixes #806
This parameter is not only used for the length of `pImageInfo`, `pBufferInfo` or `pTexelBufferView`, but also matching the value of `dataSize` when `VkWriteDescriptorSetInlineUniformBlock` is appended in `pNext`, or the value of `accelerationStructureCount` when `VkWriteDescriptorSetAccelerationStructureKHR` is in `pNext`. Having the count setter directly avaialble makes builder code more natural, instead of having to use a `mut` variable and manually assign `.descriptor_count = xx.len();` afterwards.
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkWriteDescriptorSet.html
> Enable `descriptor_count()` setter on `ash::vk::WriteDescriptorSet`

- .github/dependabot.yaml
Even though we don't have many dependencies, our GitHub Actions are getting severely out of date and are best updated to the latest version. Let dependabot help us with this, together with the few `cargo` crate dependencies that we have (mainly in examples).
> Add simple dependabot config for `cargo` and `github-actions`

- Changelog.md
- README.md
- ash-rewrite/Cargo.toml
- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash-window/README.md
- ash/Cargo.toml
- ash/src/util.rs
Some links were still pointing to the (moved) `MaikKlein/ash` repo, instead of the new shared `ash-rs/ash` repository under this organisation, GitHub still provides a redirect, but we should aim to provide the correct link from the get-go.  Only the gitter channel remains as it was impossible to get the room to be renamed.  The `ash-rs/ash` channel exists but there is currently no activity.
---
We should probably also seek to update some other external project links like the NV raytracing example, now that it has been deprecated and superseded for a while.
> Update repository links and crate keywords/categories

- Changelog.md
- ash/src/extensions/khr/ray_tracing_pipeline.rs
In an identical fashion to commit 84624fd ("ray_tracing_pipeline: Pass SBT regions as reference instead of slice (#350)") `cmd_trace_rays_indirect()` also only needs a pointer to a single `StridedDeviceAddressRegionKHR` structure.  After all no length is ever passed to the API anywhere, and this could also lead to users passing empty slices, or passing too many elements that are never used.
Clear up the confusion by replacing the slice argument with a direct borrow of the struct.
> extensions/khr/ray_tracing_pipeline: Pass indirect SBT regions as single item

- Changelog.md
- ash/Cargo.toml
- ash/src/extensions/nv/low_latency2.rs
- ash/src/vk/const_debugs.rs
- ash/src/vk/definitions.rs
- ash/src/vk/extensions.rs
Fixes https://github.com/ash-rs/ash/issues/814, CC @repi @VZout
https://github.com/KhronosGroup/Vulkan-Docs/issues/2269
> Update Vulkan-Headers to 1.3.271

- Changelog.md
- ash/src/vk/definitions.rs
- ash/src/vk/prelude.rs
- generator/src/lib.rs
It is a common operation to read and write NUL-terminated C string in the Vulkan API, yet the only helpers for that were thus far open-coded in the `Debug` printing implementations.
Move them to separate functions that are exposed to the user, in hopes of helping them no longer misunderstand NUL-terminated strings (see e.g. #830).
Important to note is that the array-copy for a static-sized `c_char` array has also been replaced with a `CStr` wrapper: this forces the user and our implementation to have a NUL-terminated string, but may now also panic if the incoming `CStr` with NUL-terminator is too large for the target `c_char` array.
> Provide `CStr` getters and setters for `c_char` pointers and arrays

- ash/src/vk/definitions.rs
- generator/src/lib.rs
Fixes #837
@Ralith I'm in quite a hurry but managed to piece together a rather minimal generator change to solve the issue, but probably did a **horrible** job of understanding, summarizing and re-explaining the issues with variance.  Feel free to suggest something better, otherwise I'll revisit it when I return.
---
In essence this builder function needs to adhere to two rules:
1. No ref-after-free: the slice must outlive (uses of) the builder object;
2. No aliasing: the slice cannot be (im)mutably used while it is mutably borrowed within a live builder object.
These two rules have been tested and are satisfied by the given builder implementation.  Without this change `timings` seems to be borrowing itself, hence is not allowed to be used after it has been temporarily mutably borrowed …
> generator: Work around invariance for assigning mutable pointer of lifetimed slice

- Changelog.md
- ash/src/vk/definitions.rs
- generator/src/lib.rs
All structs are marked as `Copy`, and builders move `self` for a convenient builder pattern directly on `default()` (using `&mut` requires first keeping the instance alive in a `let` binding).  This however leads to builder functions accidentally moving a copy of `self`, mutating it, and dropping the result directly when the caller did not consume the returned value in ad-hoc field updates, in turn leaving the author confused why their code compiles without warnings while the struct was not updated.
Annotating all Vulkan structs with `#[must_use]` should at least give them an idea why, especially because of Rust allowing us to set a custom message.
> generator: Apply `must_use` attributes to all Vulkan structs

- ash/src/vk.rs
- generator/src/lib.rs
Rust 1.75 has once again gotten a bit more complete/strict when linting code.  `.get(0)` is now recommended to be replaced with `.first()`, and needless glob reexports are equally denied (the modules in question either contain macros which are already reexported via `#[macro_export]`, or contain `impl` blocks exclusively which cannot be referred to as item paths either).
> Fix Rust 1.75 clippy lints

- generator/src/lib.rs
Upstream Vulkan is okay with the request to annotate static arrays with a `len="structField"` annotation when the size of the static arrary is bounded by a value at runtime.  This allows us to generate more convenient builder functions that copy slices into the target "builder" struct while _also_ updating the length, rather than forcing the caller to move an array of the desired length with zeroed elements and setting the length field separately.
In addition provide a safe getter (and use it in the `Debug` implementation) to return a slice view containing only valid items per the length field.  As with strings this is only possible for static-sized arrays as we can never safely dereference a random pointer.
> generator: Derive slice getters/setters for runtime-bounded static arrays

- ash/src/vk/definitions.rs
- generator/src/lib.rs
While this function is already marked `unsafe` to represent cases where an invalid pointer might be dereferenced, it should at least be obvious to the caller that there is a real chance for `NULL` pointers in these `CStr` getters, which will now be returned as `None`.  This function won't be used in `Debug` now as the dereference operation is still `unsafe`.
The `_as_c_str()` getters for static arrays is left untouched, as the data is read directly from the known-valid struct here.
> generator: Wrap `_as_c_str()` getter for possibly-pointers in `Option`

- .github/workflows/ci.yml
ash-examples has a lot of dependencies (mostly through winit), and so it's not unlikely for it to break the MSRV check. Here's the current CI error:
```
error: package `half v2.4.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0
Either upgrade to rustc 1.70 or newer, or use
cargo update -p half@2.4.0 --precise ver
where `ver` is the latest version of `half` supporting rustc 1.69.0
```
It doesn't make much sense to have our MSRV influenced by it IMO.
> Don't check MSRV for ash-examples

- ash-examples/Cargo.toml
- ash-examples/src/bin/texture.rs
- ash-examples/src/bin/triangle.rs
- ash-examples/src/lib.rs
- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash-window/examples/winit.rs
- ash-window/src/lib.rs
This is the successor to #795.  While it doesn't tackle things like backwards-compatibility nor use of the new lifetimed handles (if we _can_ even come up with a safe abstraction for them - it's very likely out of scope!), it includes the following improvements:
- Upgrade `raw-window-metal` via [#8] (Mac/iOS wasn't tested in our CI);
- Fix Windows platform types (in the `ash` crate) to be `isize` instead of `*const c_void`, matching the usptream definition;
- Update example code (impossible until `winit` with `raw-window-handle 0.6` becomes available).
[#8]: https://github.com/norse-rs/raw-window-metal/pull/8
> ash-window: Upgrade to raw-window-handle 0.6.0

- Changelog.md
- ash/src/vk.rs
- ash/src/vk/definitions.rs
- generator/src/lib.rs
Allow unsized pnext arguments for all `push_next` functions.
This allows users to write functions that receive multiple p_next structs of different types e.g.
```rust
fn create_device(p_next_structs: Vec<Box<dyn ExtendsDeviceCreateInfo>>) {
let mut device_create_info = vk::DeviceCreateInfo::builder();
for p_next_struct in &mut p_next_structs {
device_create_info = device_create_info.push_next(p_next_struct.as_mut());
}
}
```
> Allow unsized `p_next` arguments for all `push_next` functions

- Changelog.md
- ash/src/vk/definitions.rs
- generator/src/lib.rs
Oftentimes we want to populate `vk::Create*Info` and then send this struct to a worker thread for processing. This is extremely common for pipeline objects which generally takes longer than most other commands, necessitating async processing.
However, these `vk::Create*Info` structs oftentimes contain at least a `p_next` pointer which makes the struct non-Send and non-Sync. This makes sending those `vk::Create*Info` structs unnecessarily complicated.
As such, I propose that we implement "Send" and "Sync" by default for all the structs. Vulkan commands are unsafe anyways, so implementing "Send" and "Sync" shouldn't introduce additional unsafety.
> Implement `Send`/`Sync` for all `vk` structs

- README.md
Nowadays there's not much to do: get the provided SDK (ICD and VVL) from your package manager, and make sure there's a compatible Vulkan driver for the hardware installed in your machine (or an emulator like LavaPipe).  There is no longer a need to mess around with environment variables pointed out by a 7-year-old stackoverflow post, which typically leaves the Vulkan environment in a broken state instead.
> README: Modernize "install guide" for Linux systems

- Changelog.md
- ash/src/device.rs
- ash/src/instance.rs
While working on a GStreamer Vulkan interop example (where GStreamer-Vulkan opens the ICD and creates most objects for us, which need to be imported in an `ash::Instance` and `ash::Device`), it wasn't feasible to construct a `vk::EntryFnV1_0` and `vk::InstanceFnV1_0` with `extern` functions while keeping object data in some global static, especially `vk::InstanceFnV1_0` which contains many more functions that are not consumed by `Instance::load()`. GStreamer provides function loaders directly on its `GstVulkanInstance` and `GstVulkanDevice` which are desired to be used rather than attempting to open the same ICD and loading the same functions by hand.
The  original `Device::load()` and `Instance::load()` already create a closure internally, which is exactly what we need to expose to have …
> device,instance: Provide `load_with()` constructor for get_proc_addr closure

- Changelog.md
- ash/src/extensions/khr/line_rasterization.rs
- ash/src/extensions/khr/mod.rs
> extensions/khr: Add VK_KHR_line_rasterization extension

- Changelog.md
- ash/src/extensions/khr/calibrated_timestamps.rs
- ash/src/extensions/khr/mod.rs
> extensions/khr: Add VK_KHR_calibrated_timestamps

- ash/src/extensions/khr/mod.rs
While rush-rebasing 5 extensions in a row #889 seems to have ended up deleting the first line of `mod.rs`, which was defining the `acceleration_structure` module.  Restore that.
> extensions/khr: Re-add erroneously removed `mod acceleration_structure`

- ash/src/extensions/ext/extended_dynamic_state3.rs
- ash/src/extensions/ext/shader_object.rs
As stated in the vulkan specification for `vkCmdSetSampleMaskEXT`: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetSampleMaskEXT.html
`sample_mask` must be an array of size `ceil(samples/32)`. However right now the ash wrapper for this function is checking that it is of size `floor(samples/32)`, making this wrapper unusable for any sample count less than 32.
> extension/ext: Add missing length-rounding in `cmd_set_sample_mask()` assert

- ash/src/extensions_generated.rs
- ash/src/tables.rs
- generator/src/lib.rs
Seems to save about 5MiB (out of 77MiB total pre-change) in the debug build of ash-window's winit example. No obvious impact on compile time or release build size, probably because these only have one callsite each anyway in normal use. Still, seems like an easy win, might have more impact to folks who use `*Fn` directly, and it's nice to know we're not emitting a bunch of unnecessary IR.
No changelog entry as this is not a publicly-visible change.
> Outline monomorphic load functions

- Changelog.md
- ash/src/device.rs
- ash/src/extensions/amdx/shader_enqueue.rs
- ash/src/extensions/ext/shader_object.rs
- ash/src/extensions/khr/ray_tracing_pipeline.rs
- ash/src/extensions/nv/ray_tracing.rs
In `ash::Device` `create_compute_pipeline()` and `create_graphics_pipeline()` already return the list of pipelines regardless of the error code, as [documented in the Multiple Pipeline Creation chapter].  Callers are expected to scan the returned array for valid pipeline handles and either use or destroy them (when handling an error).  Furthermore, the caller is guaranteed that all handles will be NULL after the first returned NULL handle when `VK_PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT` is set.
An upstream Khronos/Vulkan request which has since been merged to the documentation makes all pipeline creation functions across the core and extensions point to this `Multiple Pipeline Creation` chapter which has also been improved, clarifying that they too return impartial results. This …
> extensions: Always return `pipeline`/`shaders`, even on error

- ash/src/extensions_generated.rs
- generator/src/lib.rs
In #894 we lost the ability to `Clone` the high-level wrappers, even though the underlying `*Fp` table and the `vk::Instance` or `vk::Device` handle themselves are `Clone`.  Restore that behaviour.
> generator: Reintroduce `Clone` on high-level `Instance`/`Device` extension wrappers

- ash/src/extensions/khr/calibrated_timestamps.rs
When introducing this new `VK_KHR_calibrated_timestamps` extension based on `VK_EXT_calibrated_timestamps` in #890 in parallel to finalizing and merging the `Instance`/`Device` separation in #734, I seem to have missed an opportunity to use the newly available `self.handle` for this extension from `struct Device`, instead leaving an unnecessary `device: vk::Device` argument in place.
> extensions/khr/calibrated_device: Use `self.handle` instead of requiring `vk::Device` argument

- ash/src/entry.rs
Use the proper name for `libvulkan.so` on Fuchsia.
> Add Fuchsia support

- Changelog.md
- README.md
- ash-window/Cargo.toml
- ash-window/Changelog.md
- ash/Cargo.toml
- ash/src/entry.rs
This is a head-start with a "little" migration guide explaining all the breaking changes we've done over the past two (!!) years, to be posted in the GitHub release (and I'm not sure if it should reside in the `keepachangelog` file).  Please let me know if there's anything breaking or otherwise important that deserves a mention.
> Release `ash 0.38.0` and `ash-window 0.13.0`

- Cargo.toml
Without a `vk-parse` change, adding `type="constants"` to `<enums>` in `vk.xml` will cause all our constants to be lost.  Use the patched crate until it's merged and released upstream, to unblock the proposed `vk.xml` change.
https://github.com/krolli/vk-parse/pull/32
https://github.com/KhronosGroup/Vulkan-Docs/pull/2366
> TEMP: Take a git reference on `vk-parse` for the upcoming `vk.xml` `<enums type="constants">` attribute

- ash/src/device.rs
- ash/src/extensions/khr/device_group.rs
- ash/src/extensions/khr/swapchain.rs
Fixes #928
In case one or more `VkResult` values returned by the underlying Vulkan function are mapped to a different return value inside `ash` for user convenience (i.e. whether a `swapchain` is suboptimal, or whether a `fence` or `event` was signaled), document explicitly what error codes from the upstream documentation result in what output values.
Note that "user convenience" here relates specifically to "success" scenarios that shouldn't be accidentally bubbled up via for example the `?` (`Try`) operator, but handled more clearly by providing a `bool` instead of forcing the user to match it out of `Err(vk::Result::*)`.
Documenting what `VkResult`s result in these `bool` return values should make it easier for the user to relate to the upstream documentation, as the naming of the …
> ash: Document `vk::Result` mapping whenever it is transformed on return

- ash-examples/src/bin/texture.rs
- ash-examples/src/bin/triangle.rs
- ash/src/device.rs
- ash/src/extensions/amd/shader_info.rs
- ash/src/extensions/nv/ray_tracing.rs
- ash/src/util.rs
`size_of(_val)()` was added to the prelude in Rust 1.80, causing `unused_qualifications` warnings whenever we import `mem` in scope and call it with `mem::` prefix.
The easiest workaround is to remove the prefix and explicitly import the function(s) in scope, which was already done in a few places.  We annotate the import with a `TODO` to remove it once bumping our MSRV on or past 1.80.
> Work around `unused_qualifications` lint for Rust 1.80 prelude extension

- generator/src/lib.rs
Some upstream `vk.xml` changes are causing failures on missing registry children later on in our generator code.  These are complicated to debug, unless we print the errors that `vk-parse` already reports.  In this debug case it was clarifying that some new and unknown elements upstream are the reason for high-level registry elements to not be parsable.
> generator: Print `vk-parse` errors when they're encountered

- Changelog.md
- ash/src/extensions/ext/metal_objects.rs
- ash/src/extensions/ext/mod.rs
A very tiny wrapper as requested by @kanerogers in https://github.com/ash-rs/ash/issues/178#issuecomment-2354489184.
> extensions/ext: Add VK_EXT_metal_objects extension

- ash-examples/src/bin/texture.rs
- ash-examples/src/bin/triangle.rs
Fixes #954
In #931 we worked around "unnecessary import" warnings for the `size_of(_val)()` functions being added to the prelude in Rust 1.80 while maintaining some form of MSRV back-compatibility (despite not testing the examples against this), but forgot about `align_of()`. This means the examples still build on Rust 1.80 or higher because `align_of()` is always in scope via the prelude there, but not on older compilers.  Fix this by adding it to the import that's tagged to be removed when we bump all of `ash` to MSRV 1.80.
> examples: Import `align_of()` from `mem` to build on on MSRV < 1.80

- generator/src/lib.rs
Fixes #959
When `vk-parse` encounters XML parsing errors (e.g. on unknown attributes or elements) it skips the element and emits an error in a list of errors that are returned to the caller.  We were originally never checking these leading to hard-to-debug issues, but eventually started asserting on this list being empty or otherwise panicking in #930.
Since `ash`'s generator is used in Khronos' upstream CI (in a fallible yet warning way), any new attribute would cause the generator to fail and subsequently require updates to `vk-parse` and `ash` before their CI is no longer flagged as "succeeded with warnings".  "Solve" this by once again allowing errors to exist, while still at least printing them to `stderr` for insights (that were previously missing...) to anyone running the …
> generator: Demote `vk-parse` error-asserts to a warning message

- ash-examples/src/bin/texture.rs
- ash-examples/src/bin/triangle.rs
- ash-examples/src/lib.rs
- ash/src/lib.rs
- ash/src/vk/definitions.rs
- generator/src/lib.rs
Rust 1.83 now detects when we unnecessarily specify lifetimes that can be omitted in `impl` blocks:
warning: the following explicit lifetimes could be elided: 'r
--> ash/src/lib.rs:85:6
|
85 | impl<'r, T> RawPtr<T> for Option<&'r T> {
|      ^^                           ^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
help: elide the lifetimes
|
85 - impl<'r, T> RawPtr<T> for Option<&'r T> {
85 + impl<T> RawPtr<T> for Option<&T> {
|
Simple manual cases are solved but autogenerated code is omitted via `allow(clippy::needless_lifetimes)` because they are incredibly hard to track correctly; we might solve these individually in followup PRs. The main cause of these violations is structs with only a reference via their …
> Fix and circumvent new Rust 1.83 lints

- Changelog.md
- ash/src/extensions/ext/tooling_info.rs
- ash/src/extensions/khr/cooperative_matrix.rs
- ash/src/extensions/khr/pipeline_executable_properties.rs
- ash/src/prelude.rs
Depends on #967
We've often discussed `pNext` chains in output arrays (i.e. #465, #588,  #744), and I always wondered why `read_into_defaulted_vector()` still existed: turns out this helper function was only hiding a few more remaining cases where the caller was previously _not_ able to manually extend the `pNext` chain to request arbitrary more structures to be filled with information.
Replace these remaining cases with a separate `_len()` getter, and have the main function take a caller-allocated `&mut [T]` slice where they can initialize the target struct including `pNext` pointer chains.
> extensions: Remove `read_into_defaulted_vector()` to let caller pass `pNext`

- Changelog.md
- README.md
- ash/src/lib.rs
- ash/src/vk/definitions.rs
- generator/src/lib.rs
Fixes #905
`push_next()` is totally `unsafe` because of dereferencing a chain of `p_next` pointers to find the end of the chain to insert, which was obfuscated by a large `unsafe` block for the `BaseOutStructure` pointer cast in commit c8c8f69a ("`next` can contain a pointer chain and we need to correct insert it.").
While this function should definitely be marked unsafe, wrapping builders in `unsafe {}` en masse in user code isn't all too desirable, especially when this soundness issue only exists to optionally walk a `p_next` chain while most users are likely inserting bare structs without pointer chains most of the time.  `push()` is introduced for this reason, remaining safe to call without any unintended raw pointer dereferences.  `push_next()` has been renamed to `extend()` to more …
> Change `push_next()` to `unsafe fn extend()` and add `push()` alternative

- ash/src/entry.rs
For OpenHarmony/HarmonyNext, we need to link `libvulkan.so` not `libvulkan.so.1`. See detail with [doc](https://developer.huawei.com/consumer/en/doc/harmonyos-references-V5/vulkan-guidelines-V5#how-to-develop)
> fix(ohos): OpenHarmony should link libvulkan.so

- ash/src/extensions_generated.rs
- generator/src/lib.rs
A `mod` importing itself hits a slow path in rustc at `compute_effective_visibilities` since cyclic imports are handled specially. This improvement also happens to greatly reduce the size of `.rmeta` files.
Self-profile of release build for `ash` on `AMD Ryzen 7 7700X`:
| Version   | `rmeta` Size | CPU Time | Real Time |
| --------- | ------------ | -------- | --------- |
| Before PR | ~68 MiB      | 15.3s    | 23.3s     |
| After PR  | ~40 MiB      | 12.6s    | 23.3s     |
| Diff      | -29 MiB      | -2.6s    | 0s        |
Elapsed real time didn't change likely because of build pipelining. I imagine weaker machines could benefit more from this. This should in general help many projects since `ash` is used in `wgpu`.
> generator: Replace `super::super::*` with narrower imports.

- Changelog.md
- ash/Cargo.toml
- ash/src/extensions/khr/acceleration_structure.rs
- ash/src/lib.rs
- ash/src/vk.rs
- ash/src/vk/definitions.rs
- ash/tests/fail/long_lived_root_struct_borrow.rs
- ash/tests/fail/long_lived_root_struct_borrow.stderr
- generator/src/lib.rs
Works towards #879, yet without swapping the generic and the struct to implement it for.
---
Instead of emitting a new `trait` for every `Root` struct that is being implemented by one or more "child" structs (those that have `Root` in their `structextends`), create one trait that takes the root struct as a generic parameter, and implement that directly instead.
This not only saves on having to define the `trait` for every `Root` struct but also paves the way towards providing default trait implementations for any pair of root and child struct, such as the `p_next` builder methods.
> generator: Replace `Extends{Root}` with `Extends<Root>` trait

- ash/Cargo.toml
Rust recently introduced the `mostly-unused` hint to speed up compilation of large crates where a significant portion of the contents are unlikely to be used concurrently.  `ash` is such a crate, which takes quite long to compile relative to the amount and kind of abstraction it provides, simply caused by the vastness of the Vulkan API (and possible remaining inefficiencies in our generated code).  This hint helps the compiler defer code generation until it knows it is definitely referenced and used, much like generics and `#[inline]` (the latter is already used consistently across this crate).  All in all this new hint [reduces compile time of the `ash` crate by about 8%](https://github.com/rust-lang/cargo/issues/15644#issuecomment-3172739856).
It however requires the use of a `nightly` …
> ash: Enable `mostly-unused` hint to speed up compilation
